"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { refreshWorkbookAssignment } from "@/actions/workbook";
import type { WorkbookAssignment } from "@/lib/workbook/select";

/**
 * Scenario brief card on the workbook tab. Shows the user's current
 * scenario (or an empty-state CTA if none yet), with a "↻ New scenario"
 * button. Clicking generates/rotates and updates inline so the brief
 * appears without a full page reload.
 */
export function WorkbookScenarioCard({
  lessonSlug,
  initialAssignment,
}: {
  lessonSlug: string;
  initialAssignment: WorkbookAssignment | null;
}) {
  const router = useRouter();
  const [assignment, setAssignment] = useState<WorkbookAssignment | null>(
    initialAssignment,
  );
  const [pending, startTransition] = useTransition();

  function rotate() {
    startTransition(async () => {
      const res = await refreshWorkbookAssignment({ lessonSlug });
      if (!res.ok) {
        toast.error(res.error);
        return;
      }
      setAssignment(res.data.assignment);
      if (res.data.generated) {
        toast.success("New scenario generated by Claude.");
      } else {
        toast.success("Switched to a different scenario.");
      }
      router.refresh();
    });
  }

  if (!assignment) {
    return (
      <section className="space-y-3">
        <div className="flex items-baseline justify-between border-b border-rule pb-2">
          <h2 className="kicker">Scenario</h2>
          <button
            type="button"
            onClick={rotate}
            disabled={pending}
            className="font-mono text-[0.7rem] uppercase tracking-[0.14em] text-muted-foreground hover:text-foreground disabled:opacity-50"
            title="Generate a fresh practice scenario for this lesson via Claude."
          >
            {pending ? "Generating…" : "Generate scenario"}
          </button>
        </div>
        <p className="text-sm text-muted-foreground">
          No scenario assigned yet. Click <em>Generate scenario</em> to draft a
          fictional case to apply your workbook against.
        </p>
      </section>
    );
  }

  return (
    <section className="space-y-3">
      <div className="flex flex-wrap items-baseline justify-between gap-3 border-b border-rule pb-2">
        <h2 className="kicker">Scenario</h2>
        <div className="flex items-center gap-3">
          {assignment.is_ai_generated ? (
            <span className="font-mono text-[0.65rem] uppercase tracking-[0.14em] text-muted-foreground">
              · AI generated
            </span>
          ) : null}
          <button
            type="button"
            onClick={rotate}
            disabled={pending}
            className="font-mono text-[0.7rem] uppercase tracking-[0.14em] text-muted-foreground hover:text-foreground disabled:opacity-50"
            title="Switch to a different scenario you haven't seen — generates a new one if the pool is exhausted."
          >
            {pending ? "Loading…" : "↻ New scenario"}
          </button>
        </div>
      </div>
      <article className="space-y-3 rounded-md border border-rule bg-paper p-4">
        <h3 className="text-base font-medium leading-snug text-ink">
          {assignment.title}
        </h3>
        <div className="whitespace-pre-wrap text-sm leading-relaxed text-ink">
          {assignment.brief}
        </div>
      </article>
    </section>
  );
}
