-- Seed 20 quiz items for Lesson 10 (schedules). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'schedules');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'schedule_literacy', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$In 'the schedule that lied every Friday,' the green status was untrue because:$$,
   $$[{"id": "a", "text": "The scheduling software had a bug"}, {"id": "b", "text": "Percentages rolled up from soft inputs — a team lead had been rounding up for weeks to avoid raising alarms"}, {"id": "c", "text": "The sponsor changed the scope"}, {"id": "d", "text": "The critical path was too short"}]$$,
   $$b$$,
   $${"a": "It wasn't a tool bug; it was optimistic human inputs aggregated.", "c": "Scope didn't change — 'nothing had changed; the green had not been true in the first place'.", "d": "Path length wasn't the issue; soft completion numbers were."}$$,
   $$medium$$),
  (2, $$The sponsor was furious primarily about:$$,
   $$[{"id": "a", "text": "The slip itself"}, {"id": "b", "text": "The surprise — 'I have been looking at green for seven weeks. What changed?'"}, {"id": "c", "text": "The cost overrun"}, {"id": "d", "text": "The vendor"}]$$,
   $$b$$,
   $${"a": "He was angry at the surprise, not the slip.", "c": "The issue was the false green, not cost.", "d": "No vendor was the cause here."}$$,
   $$easy$$),
  (3, $$The chapter's core claim about schedules is:$$,
   $$[{"id": "a", "text": "A schedule is a file you update each week"}, {"id": "b", "text": "A schedule is a model of reality you continuously verify; shallow verification turns it into a polite fiction"}, {"id": "c", "text": "A schedule is mainly a Gantt chart for sponsors"}, {"id": "d", "text": "A schedule should never change once baselined"}]$$,
   $$b$$,
   $${"a": "Treating it as a file to update is exactly the failure described.", "c": "The Gantt is presentation; the model is the point.", "d": "It must change to reflect reality."}$$,
   $$medium$$),
  (4, $$A good schedule can answer four questions at any moment. Which set?$$,
   $$[{"id": "a", "text": "Who, what, where, when"}, {"id": "b", "text": "Current end date; the critical path; what is at risk of slipping; what would push the end date out"}, {"id": "c", "text": "Budget, scope, quality, risk"}, {"id": "d", "text": "How many bars are on the Gantt"}]$$,
   $$b$$,
   $${"a": "Generic journalism questions, not the schedule's four.", "c": "Those are project variables, not the schedule's four questions.", "d": "Bar count is presentation, not insight."}$$,
   $$medium$$),
  (5, $$The most common dependency type in practice is:$$,
   $$[{"id": "a", "text": "Start-to-start"}, {"id": "b", "text": "Finish-to-start ('B cannot start until A finishes')"}, {"id": "c", "text": "Finish-to-finish"}, {"id": "d", "text": "Start-to-finish"}]$$,
   $$b$$,
   $${"a": "Possible but far less common.", "c": "Less common than finish-to-start.", "d": "The rarest of the four."}$$,
   $$easy$$),
  (6, $$The chapter says the important distinction among dependencies is:$$,
   $$[{"id": "a", "text": "The four textbook types"}, {"id": "b", "text": "The category of source — internal, external, resource, and decision"}, {"id": "c", "text": "Their duration"}, {"id": "d", "text": "Whether they are on the Gantt"}]$$,
   $$b$$,
   $${"a": "The type matters less than the source category.", "c": "Duration is a schedule attribute, not the key distinction.", "d": "Being on the Gantt doesn't categorise the dependency."}$$,
   $$medium$$),
  (7, $$Which is an EXTERNAL dependency?$$,
   $$[{"id": "a", "text": "Design must be approved before development starts"}, {"id": "b", "text": "A vendor must deliver a component / a regulatory approval must be granted"}, {"id": "c", "text": "Testing can't begin until the build is delivered"}, {"id": "d", "text": "A shared test environment is queued"}]$$,
   $$b$$,
   $${"a": "That's internal — both parties are on the project.", "c": "That's internal too.", "d": "That's a resource dependency."}$$,
   $$medium$$),
  (8, $$'A specific architect is needed but is booked on another project' is which kind of dependency?$$,
   $$[{"id": "a", "text": "Internal"}, {"id": "b", "text": "External"}, {"id": "c", "text": "Resource"}, {"id": "d", "text": "Decision"}]$$,
   $$c$$,
   $${"a": "It's not task-to-task within the project.", "b": "The architect isn't an outside party delivering to the project.", "d": "No undecided choice is blocking it; a shared resource is."}$$,
   $$medium$$),
  (9, $$Why are decision dependencies risky?$$,
   $$[{"id": "a", "text": "They are always external"}, {"id": "b", "text": "Schedules usually assume the decision will happen 'on time' without a specific plan for making that true"}, {"id": "c", "text": "They never appear on the critical path"}, {"id": "d", "text": "They are cheaper to resolve"}]$$,
   $$b$$,
   $${"a": "They're a distinct category, not necessarily external.", "c": "They frequently sit on the critical path.", "d": "Cost isn't the point; unmanaged timing is."}$$,
   $$medium$$),
  (10, $$The critical path is:$$,
   $$[{"id": "a", "text": "The most expensive activities"}, {"id": "b", "text": "The sequence of dependent activities that determines the end date — any slip on it slips the project"}, {"id": "c", "text": "The activities the sponsor cares about most"}, {"id": "d", "text": "The longest-duration single task"}]$$,
   $$b$$,
   $${"a": "Cost doesn't define criticality.", "c": "Sponsor interest doesn't define the critical path.", "d": "It's a chain of dependencies, not one task."}$$,
   $$easy$$),
  (11, $$A key property of the critical path is that:$$,
   $$[{"id": "a", "text": "It is fixed for the life of the project"}, {"id": "b", "text": "It shifts as the project progresses — slack activities become critical when earlier work slips"}, {"id": "c", "text": "Only the PM can see it"}, {"id": "d", "text": "It disappears once execution starts"}]$$,
   $$b$$,
   $${"a": "Month-1 critical path is often not month-4's.", "c": "The coordinator should know it at all times.", "d": "It's most important during execution."}$$,
   $$medium$$),
  (12, $$A 3-week slip on an OFF-critical-path activity (with sufficient slack) pushes the end date by roughly:$$,
   $$[{"id": "a", "text": "3 weeks"}, {"id": "b", "text": "Zero weeks — it consumes slack"}, {"id": "c", "text": "6 weeks"}, {"id": "d", "text": "It always becomes critical"}]$$,
   $$b$$,
   $${"a": "Only critical-path slips move the end date one-for-one.", "c": "Slack absorbs the slip; the end date doesn't move.", "d": "Only if it slips far enough to exhaust its slack."}$$,
   $$medium$$),
  (13, $$Treating all slippages as equally urgent is:$$,
   $$[{"id": "a", "text": "Correct — every slip matters the same"}, {"id": "b", "text": "A mistake — a small critical-path slip can hurt more than a large off-path one; distinguish them"}, {"id": "c", "text": "Fine if you have buffer"}, {"id": "d", "text": "Only a problem in agile"}]$$,
   $$b$$,
   $${"a": "Slips on slack and on the critical path differ enormously.", "c": "Buffer doesn't make the distinction unnecessary.", "d": "It applies to any methodology."}$$,
   $$medium$$),
  (14, $$'Float' (or slack) is:$$,
   $$[{"id": "a", "text": "Intentional contingency built into the schedule"}, {"id": "b", "text": "The amount of time a non-critical activity can slip without affecting the end date"}, {"id": "c", "text": "The total project duration"}, {"id": "d", "text": "Padding added to every task"}]$$,
   $$b$$,
   $${"a": "That describes buffer, a different concept.", "c": "Float is per-activity slack, not total duration.", "d": "Per-task padding is the anti-pattern, not float."}$$,
   $$medium$$),
  (15, $$The chapter's recommended way to hold buffer is:$$,
   $$[{"id": "a", "text": "Pad every activity by 20%"}, {"id": "b", "text": "A small number of named reserves held at specific points by the PM (before milestones, integrations, external dependencies)"}, {"id": "c", "text": "Add buffer only at the very end"}, {"id": "d", "text": "Never use buffer"}]$$,
   $$b$$,
   $${"a": "Per-task padding gets unconsciously consumed and hides true status.", "c": "Buffer belongs before key risk points, not just the end.", "d": "Mature practice uses explicit buffer."}$$,
   $$medium$$),
  (16, $$Burning buffer faster than you are burning work is:$$,
   $$[{"id": "a", "text": "Normal and expected"}, {"id": "b", "text": "A warning sign that the estimates were optimistic — information the PM needs"}, {"id": "c", "text": "A sign the project is ahead"}, {"id": "d", "text": "Irrelevant"}]$$,
   $$b$$,
   $${"a": "It's a red flag, not routine.", "c": "It's the opposite of being ahead.", "d": "It's exactly the kind of signal to surface."}$$,
   $$medium$$),
  (17, $$Which is EVIDENCE of completion rather than assertion?$$,
   $$[{"id": "a", "text": "'We're tracking well'"}, {"id": "b", "text": "'Eight of the ten sub-tasks are done, and the remaining two have an estimated four days left"}, {"id": "c", "text": "'It's basically there'"}, {"id": "d", "text": "'Trust me, it's fine'"}]$$,
   $$b$$,
   $${"a": "That's an assertion with no basis.", "c": "Vague reassurance, not evidence.", "d": "Assertion, not evidence."}$$,
   $$easy$$),
  (18, $$For short work packages, the chapter recommends tracking:$$,
   $$[{"id": "a", "text": "Percent complete to one decimal place"}, {"id": "b", "text": "Binary or coarse status — not started / in progress / done"}, {"id": "c", "text": "Hours remaining, hourly"}, {"id": "d", "text": "A daily Gantt update"}]$$,
   $$b$$,
   $${"a": "Percent complete on a two-week task is noise.", "c": "Hourly tracking is overkill and inaccurate.", "d": "Daily Gantt churn doesn't improve accuracy."}$$,
   $$medium$$),
  (19, $$A package estimated at 80 hours is reported '50% complete' but the team has logged 60 hours. This means:$$,
   $$[{"id": "a", "text": "Everything is on track"}, {"id": "b", "text": "Something is wrong — the estimate was low, the report is optimistic, or hours are miscategorised"}, {"id": "c", "text": "The package is ahead of schedule"}, {"id": "d", "text": "Nothing — hours don't matter"}]$$,
   $$b$$,
   $${"a": "60 hours for half of an 80-hour package signals trouble.", "c": "It's behind, if anything.", "d": "Cross-checking actuals against reported progress is exactly the discipline."}$$,
   $$medium$$),
  (20, $$The chapter's discipline for keeping the schedule honest includes walking the critical path:$$,
   $$[{"id": "a", "text": "Once at the start of the project"}, {"id": "b", "text": "Weekly — getting real status from the person doing the work, not just the workstream lead"}, {"id": "c", "text": "Only when a slip is reported"}, {"id": "d", "text": "Never — trust the dashboard"}]$$,
   $$b$$,
   $${"a": "It shifts over time, so a one-time walk isn't enough.", "c": "Weekly walking catches problems before they're reported.", "d": "The 20-minute walk beats any dashboard."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'schedules'
on conflict do nothing;
