-- Seed 20 quiz items for Lesson 17 (push-back). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'push-back');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'pushback_judgment', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$In the Thursday-deliverable story, why was the coordinator 'part of the failure' despite being blameless?$$,
   $$[{"id": "a", "text": "They sent the wrong file"}, {"id": "b", "text": "They flagged the concern at the lowest intensity ('Are you sure?') and accepted the overrule without pressing"}, {"id": "c", "text": "They refused to send it"}, {"id": "d", "text": "They never noticed the issue"}]$$,
   $$b$$,
   $${"a": "The right file was sent — with provisional numbers.", "c": "They sent it; they didn't refuse.", "d": "They noticed and flagged — just too weakly."}$$,
   $$medium$$),
  (2, $$Push-back is warranted when all FOUR of which conditions are present?$$,
   $$[{"id": "a", "text": "You outrank the person, it's urgent, it's documented, and it's your job"}, {"id": "b", "text": "Stakes are material; you have relevant information the senior may not; the decision is costly to reverse if wrong; the senior is deciding under time pressure or incomplete information"}, {"id": "c", "text": "You disagree, you're confident, you're busy, and you're tired"}, {"id": "d", "text": "The sponsor is watching, it's Friday, it's a big number, and it's risky"}]$$,
   $$b$$,
   $${"a": "None of those are the four conditions.", "c": "Mere disagreement and mood aren't the conditions.", "d": "Those aren't the chapter's four conditions."}$$,
   $$hard$$),
  (3, $$Pushing back is:$$,
   $$[{"id": "a", "text": "The same as disagreeing — push back every time you disagree"}, {"id": "b", "text": "NOT the same as disagreeing — you disagree often but only push back when the four conditions hold"}, {"id": "c", "text": "Only ever done in writing"}, {"id": "d", "text": "Always insubordinate"}]$$,
   $$b$$,
   $${"a": "You'd be pushing constantly; that's not the point.", "c": "Often it's better verbal.", "d": "Done well, it's explicitly not insubordination."}$$,
   $$medium$$),
  (4, $$A small formatting preference from the PM that you think is wrong is:$$,
   $$[{"id": "a", "text": "Worth a firm push-back"}, {"id": "b", "text": "Not worth a push — the stakes aren't material"}, {"id": "c", "text": "Grounds for escalation"}, {"id": "d", "text": "A reason to ignore the PM"}]$$,
   $$b$$,
   $${"a": "Low stakes don't warrant a push.", "c": "Escalation is for serious, unresolved issues.", "d": "You'd simply do it; it's not push-worthy."}$$,
   $$easy$$),
  (5, $$The chapter's method for pushing back well is to:$$,
   $$[{"id": "a", "text": "Refuse and explain later"}, {"id": "b", "text": "State the concern specifically and briefly, make the consequence concrete, offer an alternative, and accept the decision if overruled"}, {"id": "c", "text": "Send a long email to everyone"}, {"id": "d", "text": "Hint at the problem and hope they notice"}]$$,
   $$b$$,
   $${"a": "Refusal isn't the method; flag-recommend-defer is.", "c": "Broadcasting isn't push-back.", "d": "Hinting (the 'are you sure?' failure) is exactly what to avoid."}$$,
   $$medium$$),
  (6, $$The chapter's script — 'Before I do this, I want to flag something — [concern]. My recommendation would be [alternative]. But if you've thought about this and still want me to proceed, I'll proceed' — works because it:$$,
   $$[{"id": "a", "text": "Refuses the instruction outright"}, {"id": "b", "text": "States the concern, offers an alternative, AND explicitly accepts the senior person's authority to overrule — so it can't reasonably be read as insubordination"}, {"id": "c", "text": "Avoids mentioning the concern"}, {"id": "d", "text": "Threatens to escalate"}]$$,
   $$b$$,
   $${"a": "It doesn't refuse — it defers to the decision.", "c": "It states the concern clearly.", "d": "No threat; it offers and defers."}$$,
   $$medium$$),
  (7, $$If the PM considers your push-back and still says proceed, you should:$$,
   $$[{"id": "a", "text": "Keep relitigating until they change their mind"}, {"id": "b", "text": "Proceed without relitigating — you've done your job"}, {"id": "c", "text": "Escalate over their head"}, {"id": "d", "text": "Refuse to proceed"}]$$,
   $$b$$,
   $${"a": "Relitigating after a decision tips into insubordination.", "c": "Going over their head breaks the channels.", "d": "Refusing after an informed overrule is insubordination."}$$,
   $$medium$$),
  (8, $$The right posture when pushing back is:$$,
   $$[{"id": "a", "text": "Accusatory — point out the PM is wrong"}, {"id": "b", "text": "Respectful but clear — offering information and a recommendation, not accusing"}, {"id": "c", "text": "Apologetic and tentative"}, {"id": "d", "text": "Silent but resentful"}]$$,
   $$b$$,
   $${"a": "Accusation damages the relationship.", "c": "Tentativeness is the lowest-intensity failure.", "d": "Silence is the under-push failure."}$$,
   $$medium$$),
  (9, $$On written versus verbal push-back, the chapter's rule is:$$,
   $$[{"id": "a", "text": "Always put it in writing"}, {"id": "b", "text": "For everyday pushes, talk (softer, less paper trail); for consequential pushes where you want a record, write"}, {"id": "c", "text": "Always do it verbally"}, {"id": "d", "text": "Never write anything down"}]$$,
   $$b$$,
   $${"a": "Everyday pushes are better verbal.", "c": "High-stakes pushes benefit from a record.", "d": "A record protects both parties on consequential calls."}$$,
   $$medium$$),
  (10, $$Why do coordinators commonly fail to push back?$$,
   $$[{"id": "a", "text": "They never have concerns"}, {"id": "b", "text": "Hierarchy, information asymmetry, relational cost, speed, and self-doubt — each has some merit, but none justifies silence on something consequential"}, {"id": "c", "text": "It is against company policy"}, {"id": "d", "text": "Push-back is illegal"}]$$,
   $$b$$,
   $${"a": "They have concerns but stay silent.", "c": "No policy forbids it.", "d": "It's a professional act, not illegal."}$$,
   $$medium$$),
  (11, $$The deeper failure mode the chapter warns about is:$$,
   $$[{"id": "a", "text": "Pushing back too often"}, {"id": "b", "text": "Letting the reasons-not-to compound until the default becomes 'never push back, ever' — a different failure than the occasional wrong push"}, {"id": "c", "text": "Documenting too much"}, {"id": "d", "text": "Being too direct"}]$$,
   $$b$$,
   $${"a": "That's a separate, lesser risk.", "c": "Records aren't the failure.", "d": "Directness, done respectfully, is the goal."}$$,
   $$medium$$),
  (12, $$Which is a specific, well-stated concern (not the weak version)?$$,
   $$[{"id": "a", "text": "'I have some concerns about this'"}, {"id": "b", "text": "'The supporting analysis isn't in yet; the numbers in the draft could shift materially when it lands'"}, {"id": "c", "text": "'Are you sure?'"}, {"id": "d", "text": "'This feels off'"}]$$,
   $$b$$,
   $${"a": "Vague — no specifics.", "c": "The lowest-intensity flag that failed in the story.", "d": "A feeling, not a concrete concern."}$$,
   $$medium$$),
  (13, $$'Making the consequence concrete' sounds like:$$,
   $$[{"id": "a", "text": "'This could be bad'"}, {"id": "b", "text": "'If the client uses these figures and the analysis changes them significantly, we'll have to issue a correction'"}, {"id": "c", "text": "'I wouldn't do it'"}, {"id": "d", "text": "'Trust me on this'"}]$$,
   $$b$$,
   $${"a": "Vague stakes.", "c": "A preference, not a concrete consequence.", "d": "An appeal, not a consequence."}$$,
   $$medium$$),
  (14, $$A good alternative to offer in push-back is:$$,
   $$[{"id": "a", "text": "'Just don't send it'"}, {"id": "b", "text": "'Could we send a short note saying the full analysis arrives Monday, and defer the full deliverable until then?'"}, {"id": "c", "text": "'Do whatever you want'"}, {"id": "d", "text": "'That's your call'"}]$$,
   $$b$$,
   $${"a": "A bare refusal isn't an alternative.", "c": "Abdicating isn't an alternative.", "d": "That's deferring without offering a path."}$$,
   $$medium$$),
  (15, $$When asked to do something outside your role/scope, the chapter recommends saying yes:$$,
   $$[{"id": "a", "text": "Immediately, to be helpful"}, {"id": "b", "text": "Carefully — 'Happy to help — can I check with the PM first?' or 'is it in scope, or would we need a CR?' — professional reframings that route the request"}, {"id": "c", "text": "With a flat refusal"}, {"id": "d", "text": "Only if the sponsor asks"}]$$,
   $$b$$,
   $${"a": "Immediate yes risks unauthorised work.", "c": "These are reframings, not refusals.", "d": "It applies to any out-of-scope request."}$$,
   $$medium$$),
  (16, $$The 'say yes carefully' reframings are best understood as:$$,
   $$[{"id": "a", "text": "Refusals dressed up politely"}, {"id": "b", "text": "Professional reframings that route the request through the right process and protect you from unauthorised work"}, {"id": "c", "text": "A way to avoid all work"}, {"id": "d", "text": "Insubordination"}]$$,
   $$b$$,
   $${"a": "They're not refusals — they route the request.", "c": "They route, not dodge, the work.", "d": "They're professional, not insubordinate."}$$,
   $$medium$$),
  (17, $$'Pushing back on yourself' refers to:$$,
   $$[{"id": "a", "text": "Second-guessing every decision endlessly"}, {"id": "b", "text": "Listening to the internal voice that says a take-the-easy-path move is wrong — professionals who can't push back internally can't push back externally"}, {"id": "c", "text": "Blaming yourself for others' mistakes"}, {"id": "d", "text": "Avoiding all risk"}]$$,
   $$b$$,
   $${"a": "It's about heeding a real signal, not endless doubt.", "c": "It's self-honesty, not self-blame.", "d": "It's about judgment, not risk-avoidance."}$$,
   $$medium$$),
  (18, $$A written push-back, per the chapter, is valuable on consequential calls because it:$$,
   $$[{"id": "a", "text": "Embarrasses the PM"}, {"id": "b", "text": "Creates a dated, timestamped record that, if things go sideways, shows you flagged appropriately and protects both parties"}, {"id": "c", "text": "Forces the PM to agree"}, {"id": "d", "text": "Replaces the conversation entirely"}]$$,
   $$b$$,
   $${"a": "It should still be respectful, not embarrassing.", "c": "It records the exchange; it doesn't force agreement.", "d": "It complements, not replaces, the judgement."}$$,
   $$medium$$),
  (19, $$You should probably NOT push back when:$$,
   $$[{"id": "a", "text": "All four conditions are present"}, {"id": "b", "text": "Only one or two of the four conditions are present"}, {"id": "c", "text": "The decision is costly to reverse and you have unique information"}, {"id": "d", "text": "The senior person is rushed and the stakes are material"}]$$,
   $$b$$,
   $${"a": "That's exactly when you SHOULD push.", "c": "Those are two of the conditions — push-worthy if the others hold.", "d": "Those are conditions present — lean toward pushing."}$$,
   $$medium$$),
  (20, $$The chapter's advice for building the push-back muscle is to:$$,
   $$[{"id": "a", "text": "Only ever push on the highest-stakes issues"}, {"id": "b", "text": "Practice one small, low-stakes push in a PM one-on-one ('I'd do X differently, here's why') so the high-stakes version feels more natural"}, {"id": "c", "text": "Never push until you're senior"}, {"id": "d", "text": "Push back on everything to get used to it"}]$$,
   $$b$$,
   $${"a": "Practising on low-stakes items builds the skill.", "c": "Waiting for seniority is how the never-push default forms.", "d": "Pushing on everything is the over-push failure."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'push-back'
on conflict do nothing;
