-- Seed 20 quiz items for Lesson 12 (minutes). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'minutes');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'minutes_discipline', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$In the chapter's story, a vendor dispute 18 months later was resolved by:$$,
   $$[{"id": "a", "text": "The coordinator's memory of the kickoff"}, {"id": "b", "text": "Carefully-written kickoff minutes — sent to all attendees and accepted by silence — that recorded D and E as out of scope"}, {"id": "c", "text": "A new negotiation with the vendor"}, {"id": "d", "text": "The original signed contract alone"}]$$,
   $$b$$,
   $${"a": "The coordinator did NOT remember — the minutes did the work.", "c": "No renegotiation — the record settled it ('closed by good paperwork').", "d": "It was the minutes, accepted by silence, that clarified scope."}$$,
   $$medium$$),
  (2, $$Minutes are best understood as:$$,
   $$[{"id": "a", "text": "A transcript of everything said"}, {"id": "b", "text": "A structured record of decisions, actions, and key context"}, {"id": "c", "text": "A narrative summary of the discussion"}, {"id": "d", "text": "An optional courtesy"}]$$,
   $$b$$,
   $${"a": "Transcripts are almost never useful — minutes are structured.", "c": "Narrative prose is exactly what minutes leave out.", "d": "They're a durable, legal-ish record, not optional."}$$,
   $$easy$$),
  (3, $$The three components minutes must capture are:$$,
   $$[{"id": "a", "text": "Attendance, duration, and agenda"}, {"id": "b", "text": "Decisions, actions, and key context (only when necessary)"}, {"id": "c", "text": "Discussion, side remarks, and compliments"}, {"id": "d", "text": "Risks, issues, and dependencies"}]$$,
   $$b$$,
   $${"a": "Those are header details, not the core content.", "c": "Those are exactly what does NOT belong in minutes.", "d": "That's the RAID log, a different artifact."}$$,
   $$medium$$),
  (4, $$Which is a properly written action?$$,
   $$[{"id": "a", "text": "The team will investigate the vendor issue"}, {"id": "b", "text": "Priya will investigate the vendor issue and report back by May 15"}, {"id": "c", "text": "We should look into the vendor situation"}, {"id": "d", "text": "Vendor issue — ongoing"}]$$,
   $$b$$,
   $${"a": "'The team will' has no single owner — not an action.", "c": "Vague, no owner, no date.", "d": "No owner and no due date."}$$,
   $$easy$$),
  (5, $$Every action entry must have exactly:$$,
   $$[{"id": "a", "text": "One owner"}, {"id": "b", "text": "Two reviewers"}, {"id": "c", "text": "As many owners as are involved"}, {"id": "d", "text": "No owner — ownership is collective"}]$$,
   $$a$$,
   $${"b": "Reviewers aren't required; a single accountable owner is.", "c": "Multiple owners means no one is accountable.", "d": "Collective ownership is diffuse ownership."}$$,
   $$medium$$),
  (6, $$Narrative entries like 'The team discussed the timeline at length' belong:$$,
   $$[{"id": "a", "text": "In the Decisions section"}, {"id": "b", "text": "Nowhere — if it's worth recording it's a decision, an action, or brief context"}, {"id": "c", "text": "In the Actions table"}, {"id": "d", "text": "At the top of the minutes"}]$$,
   $$b$$,
   $${"a": "Discussion isn't a decision.", "c": "It's not an action either.", "d": "The top holds the meeting header, not prose."}$$,
   $$medium$$),
  (7, $$The recommended Actions section format is:$$,
   $$[{"id": "a", "text": "A paragraph of prose"}, {"id": "b", "text": "A table/list with columns: action, owner, due date, status (status starts 'open')"}, {"id": "c", "text": "A single bullet per meeting"}, {"id": "d", "text": "Whatever the chair prefers each week"}]$$,
   $$b$$,
   $${"a": "Prose hides owners and dates.", "c": "Each action needs its own row with owner/date.", "d": "Consistency across meetings is the point."}$$,
   $$medium$$),
  (8, $$The chapter says to write minutes:$$,
   $$[{"id": "a", "text": "From memory, a day or two later"}, {"id": "b", "text": "In real time during the meeting — reconstruction introduces errors"}, {"id": "c", "text": "Only after the PM dictates them"}, {"id": "d", "text": "As a full transcript first, then trim"}]$$,
   $$b$$,
   $${"a": "Reconstruction is exactly what introduces errors.", "c": "The coordinator captures live, not by dictation.", "d": "Transcribing everything is wasted effort."}$$,
   $$medium$$),
  (9, $$Minutes should be sent:$$,
   $$[{"id": "a", "text": "Within a week"}, {"id": "b", "text": "Within 24 hours, ideally same-day; more than 48 hours is a warning sign"}, {"id": "c", "text": "Only when requested"}, {"id": "d", "text": "At month-end with all other minutes"}]$$,
   $$b$$,
   $${"a": "A week later, nobody reads them.", "c": "They go out proactively, same-day.", "d": "Batching defeats the purpose."}$$,
   $$easy$$),
  (10, $$Writing 'the team agreed' in minutes means:$$,
   $$[{"id": "a", "text": "Most people nodded"}, {"id": "b", "text": "The room was unanimous — these words carry weight and shouldn't be used loosely"}, {"id": "c", "text": "The PM decided"}, {"id": "d", "text": "Nothing in particular"}]$$,
   $$b$$,
   $${"a": "'Agreed' asserts unanimity, not a majority nod.", "c": "That would be 'the PM decided/approved'.", "d": "Attribution words have real weight in the record."}$$,
   $$medium$$),
  (11, $$If your notes have an unresolved question before the minutes go out, you should:$$,
   $$[{"id": "a", "text": "Send them with a 'TBD' entry"}, {"id": "b", "text": "Resolve it first — a quick Slack to the PM or relevant party — rather than publishing an incomplete record"}, {"id": "c", "text": "Leave it out silently"}, {"id": "d", "text": "Guess the most likely answer"}]$$,
   $$b$$,
   $${"a": "'TBD' entries signal an incomplete meeting.", "c": "Silently dropping a decision corrupts the record.", "d": "Guessing risks recording the wrong thing."}$$,
   $$medium$$),
  (12, $$The register of minutes should be:$$,
   $$[{"id": "a", "text": "Conversational, with a bit of humour"}, {"id": "b", "text": "Formal, neutral, and spare — even when the meeting was contentious"}, {"id": "c", "text": "Emotive, to convey how the room felt"}, {"id": "d", "text": "Evaluative, judging who was right"}]$$,
   $$b$$,
   $${"a": "No contractions, humour, or editorialising.", "c": "Emotion doesn't hold up for later readers.", "d": "Minutes record what happened without evaluating it."}$$,
   $$medium$$),
  (13, $$A senior stakeholder argued forcefully for a rejected position. The neutral minute reads:$$,
   $$[{"id": "a", "text": "X was pushed back on heavily and lost"}, {"id": "b", "text": "X was discussed; after review, the committee decided to proceed with Y; concerns raised by [name] regarding [issue] added to the risk register"}, {"id": "c", "text": "X was a bad idea, so we went with Y"}, {"id": "d", "text": "X was defeated after a heated argument"}]$$,
   $$b$$,
   $${"a": "Evaluative and embarrassing to a named party.", "c": "Editorialising ('bad idea') has no place in minutes.", "d": "'Heated argument' is colour, not record."}$$,
   $$hard$$),
  (14, $$The action tracker is:$$,
   $$[{"id": "a", "text": "The same thing as the minutes"}, {"id": "b", "text": "A living operational view of all open actions across meetings — separate from, and more useful than, the static minutes"}, {"id": "c", "text": "A list the PM keeps privately"}, {"id": "d", "text": "Only needed for steering committees"}]$$,
   $$b$$,
   $${"a": "Minutes are static records; the tracker is a living view.", "c": "The coordinator typically maintains it.", "d": "It serves all standing meetings."}$$,
   $$medium$$),
  (15, $$The first agenda item of most standing meetings should be:$$,
   $$[{"id": "a", "text": "A round of introductions"}, {"id": "b", "text": "A 30-second review of last meeting's actions — what's complete, on track, overdue"}, {"id": "c", "text": "The sponsor's update"}, {"id": "d", "text": "Any other business"}]$$,
   $$b$$,
   $${"a": "Introductions aren't a standing-meeting opener.", "c": "Action review comes first to keep commitments real.", "d": "AOB is typically last, not first."}$$,
   $$medium$$),
  (16, $$The chapter's advice on chasing overdue actions is to:$$,
   $$[{"id": "a", "text": "Call them out publicly in the next meeting every time"}, {"id": "b", "text": "Chase privately first ('any obstacles?'); reserve public reminders for chronic cases or genuine escalation"}, {"id": "c", "text": "Ignore them until the owner raises them"}, {"id": "d", "text": "Escalate immediately to the sponsor"}]$$,
   $$b$$,
   $${"a": "Public reminders are for chronic/escalation cases, not routine.", "c": "Tracking and chasing is the discipline, not waiting.", "d": "Private nudge first; sponsor escalation is a last resort."}$$,
   $$medium$$),
  (17, $$Steering-committee / sponsor-level minutes should be:$$,
   $$[{"id": "a", "text": "The lightest, fastest minutes you write"}, {"id": "b", "text": "Your most carefully written — precise language, PM review before sending"}, {"id": "c", "text": "Skipped, since the sponsor was there"}, {"id": "d", "text": "Identical in care to weekly team minutes"}]$$,
   $$b$$,
   $${"a": "They're the most carefully written, not the lightest.", "c": "They're referenced formally later — never skip.", "d": "They warrant extra care beyond weekly minutes."}$$,
   $$medium$$),
  (18, $$An important decision emerging from an informal one-on-one should be:$$,
   $$[{"id": "a", "text": "Left undocumented — informal chats don't get minutes"}, {"id": "b", "text": "Confirmed afterward with a brief written summary to the relevant parties"}, {"id": "c", "text": "Added to the next steering committee agenda only"}, {"id": "d", "text": "Recorded as full formal minutes"}]$$,
   $$b$$,
   $${"a": "The commitment still needs a written confirmation.", "c": "A quick written confirmation is enough and timely.", "d": "Full minutes are overkill for a one-on-one."}$$,
   $$medium$$),
  (19, $$When someone challenges your minutes ('I didn't say that'), the right posture is:$$,
   $$[{"id": "a", "text": "Defensive — insist you're right"}, {"id": "b", "text": "Neutral and evidence-based — compare against your notes, check with another attendee, and have the chair rule on genuine disagreement"}, {"id": "c", "text": "Apologetic — change it to whatever they prefer"}, {"id": "d", "text": "Quietly revise it to match their preference"}]$$,
   $$b$$,
   $${"a": "Defensiveness isn't the posture; evidence is.", "c": "Don't just capitulate — check the record.", "d": "Silent revision of a legal-ish document is worse than the original error."}$$,
   $$medium$$),
  (20, $$If minutes need correcting after issue, you should:$$,
   $$[{"id": "a", "text": "Quietly edit the original and resend with no note"}, {"id": "b", "text": "Reissue openly with a brief, transparent correction note"}, {"id": "c", "text": "Leave the error — minutes can't be changed"}, {"id": "d", "text": "Delete the original entirely"}]$$,
   $$b$$,
   $${"a": "Silent revision is exactly what the chapter forbids.", "c": "They can be corrected — openly.", "d": "Deleting destroys the record; you correct transparently."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'minutes'
on conflict do nothing;
