-- Seed 20 quiz items for Lesson 25 (coordinator-to-pm). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'coordinator-to-pm');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'career_pathing', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$The central shift from coordinator to project manager is:$$,
   $$[{"id": "a", "text": "From doing more tasks to doing them faster"}, {"id": "b", "text": "From keeping the work visible and on-track to OWNING the outcome — making the decisions and being accountable for the result"}, {"id": "c", "text": "From junior to senior pay"}, {"id": "d", "text": "From part-time to full-time"}]$$,
   $$b$$,
   $${"a": "It's a shift in responsibility, not throughput.", "c": "Pay may follow but isn't the shift itself.", "d": "It's about ownership, not hours."}$$,
   $$medium$$),
  (2, $$A coordinator surfaces issues and options; a PM additionally:$$,
   $$[{"id": "a", "text": "Surfaces them faster"}, {"id": "b", "text": "Makes the call and owns the consequences of the decision"}, {"id": "c", "text": "Escalates everything upward"}, {"id": "d", "text": "Avoids decisions to stay neutral"}]$$,
   $$b$$,
   $${"a": "The difference is decision ownership, not speed.", "c": "A PM decides rather than escalating everything.", "d": "PMs must decide, not stay neutral."}$$,
   $$medium$$),
  (3, $$The chapter says the best preparation for the PM role is to:$$,
   $$[{"id": "a", "text": "Wait until you're promoted to start thinking like a PM"}, {"id": "b", "text": "Start exercising judgement now — form a view on decisions before they're made and check it against what actually happens"}, {"id": "c", "text": "Take a certification first"}, {"id": "d", "text": "Avoid responsibility until the title is official"}]$$,
   $$b$$,
   $${"a": "You build the muscle before the title.", "c": "Certifications help but practice judgement is the core.", "d": "Stepping up early is the preparation."}$$,
   $$medium$$),
  (4, $$'Forming a view before the decision is made' helps you grow because:$$,
   $$[{"id": "a", "text": "It guarantees you'll be right"}, {"id": "b", "text": "Comparing your prediction to the actual outcome calibrates your judgement over time"}, {"id": "c", "text": "It impresses the PM"}, {"id": "d", "text": "It lets you take credit"}]$$,
   $$b$$,
   $${"a": "It's about calibration, not always being right.", "c": "The benefit is your own growth, not optics.", "d": "It isn't about claiming credit."}$$,
   $$medium$$),
  (5, $$The deepest credibility a future PM builds comes from:$$,
   $$[{"id": "a", "text": "A polished CV"}, {"id": "b", "text": "A track record of reliability and good judgement that the people around you have witnessed"}, {"id": "c", "text": "Knowing the most jargon"}, {"id": "d", "text": "Having the most certifications"}]$$,
   $$b$$,
   $${"a": "Demonstrated trust outweighs a document.", "c": "Vocabulary isn't credibility.", "d": "Certifications support but don't substitute for a track record."}$$,
   $$medium$$),
  (6, $$Moving up means moving from accountability for tasks to accountability for:$$,
   $$[{"id": "a", "text": "Nothing — managers delegate it all"}, {"id": "b", "text": "Outcomes — including for work done by others on the team"}, {"id": "c", "text": "Only your own work"}, {"id": "d", "text": "Just the schedule"}]$$,
   $$b$$,
   $${"a": "Accountability grows, it doesn't disappear.", "c": "It expands beyond your own tasks.", "d": "It covers the whole outcome, not one dimension."}$$,
   $$medium$$),
  (7, $$To develop, the chapter advises seeking out:$$,
   $$[{"id": "a", "text": "Only the work you already do well"}, {"id": "b", "text": "Stretch responsibilities slightly beyond your current role, with support, so you build new capability before the title"}, {"id": "c", "text": "Tasks no one else wants, regardless of value"}, {"id": "d", "text": "A complete change of field"}]$$,
   $$b$$,
   $${"a": "Comfortable work doesn't stretch you.", "c": "Stretch should be meaningful, not just unwanted scraps.", "d": "You build on your foundation, not abandon it."}$$,
   $$medium$$),
  (8, $$A good way to learn PM judgement from your current PM is to:$$,
   $$[{"id": "a", "text": "Copy their style exactly"}, {"id": "b", "text": "Watch HOW and WHY they make decisions — the reasoning, not just the outcome — and ask about the calls you didn't understand"}, {"id": "c", "text": "Only observe their successes"}, {"id": "d", "text": "Avoid questioning their decisions"}]$$,
   $$b$$,
   $${"a": "You learn the reasoning, not a style to mimic.", "c": "The hard calls teach the most.", "d": "Asking why is how you learn, done respectfully."}$$,
   $$medium$$),
  (9, $$The chapter frames mistakes made while stretching as:$$,
   $$[{"id": "a", "text": "Proof you aren't ready"}, {"id": "b", "text": "Part of how judgement is built — provided you own them, learn, and don't repeat them"}, {"id": "c", "text": "Something to hide"}, {"id": "d", "text": "The PM's fault"}]$$,
   $$b$$,
   $${"a": "Stretching means occasional misses; that's normal growth.", "c": "Owning beats hiding.", "d": "You own your own mistakes."}$$,
   $$medium$$),
  (10, $$Which skill transfers MOST directly from coordinator to PM?$$,
   $$[{"id": "a", "text": "None — it's a clean break"}, {"id": "b", "text": "The hard-won habits of reliability, communication, and seeing the whole project — the PM builds decision ownership ON TOP of these"}, {"id": "c", "text": "Only administrative skills"}, {"id": "d", "text": "Only technical skills"}]$$,
   $$b$$,
   $${"a": "It builds on the coordinator foundation, not a break.", "c": "Far more than admin transfers.", "d": "The transferable core is broader than technical skill."}$$,
   $$medium$$),
  (11, $$Owning an outcome you can't fully control (because others do the work) requires:$$,
   $$[{"id": "a", "text": "Doing all the work yourself"}, {"id": "b", "text": "Influence, clear expectations, and follow-through — getting results through others rather than by personal effort alone"}, {"id": "c", "text": "Blaming the team when it slips"}, {"id": "d", "text": "Refusing the accountability"}]$$,
   $$b$$,
   $${"a": "You can't personally do everything; you lead it.", "c": "Ownership means not deflecting blame.", "d": "The role requires accepting the accountability."}$$,
   $$hard$$),
  (12, $$The chapter's view on titles vs capability is:$$,
   $$[{"id": "a", "text": "The title comes first and capability follows"}, {"id": "b", "text": "Build the capability first; the title tends to follow demonstrated readiness, not the other way round"}, {"id": "c", "text": "Titles are all that matter"}, {"id": "d", "text": "Capability is irrelevant without a title"}]$$,
   $$b$$,
   $${"a": "Readiness generally precedes the title.", "c": "Capability is what the title should recognise.", "d": "Capability matters with or without the title."}$$,
   $$medium$$),
  (13, $$Making your growth ambitions known to your manager is advised because:$$,
   $$[{"id": "a", "text": "It pressures them into promoting you"}, {"id": "b", "text": "They can only give you stretch opportunities and sponsorship if they know what you're aiming for"}, {"id": "c", "text": "It is required by HR"}, {"id": "d", "text": "It guarantees a promotion"}]$$,
   $$b$$,
   $${"a": "It's about enabling support, not pressure.", "c": "It's good practice, not a requirement.", "d": "It improves your odds, not a guarantee."}$$,
   $$medium$$),
  (14, $$A coordinator demonstrating PM-readiness handles ambiguity by:$$,
   $$[{"id": "a", "text": "Waiting for explicit instructions on everything"}, {"id": "b", "text": "Taking sensible initiative within their remit, proposing a path forward rather than only flagging the problem"}, {"id": "c", "text": "Making unilateral high-stakes decisions outside their authority"}, {"id": "d", "text": "Ignoring the ambiguity"}]$$,
   $$b$$,
   $${"a": "Always waiting signals you're not ready to step up.", "c": "Overstepping authority is the opposite error.", "d": "Ignoring it isn't initiative."}$$,
   $$hard$$),
  (15, $$As you take on more decision ownership, your relationship to being wrong should be:$$,
   $$[{"id": "a", "text": "Never be wrong"}, {"id": "b", "text": "Accept that owning decisions means sometimes being wrong, and build the judgement to be wrong less often and recover well"}, {"id": "c", "text": "Avoid decisions to avoid being wrong"}, {"id": "d", "text": "Blame the data"}]$$,
   $$b$$,
   $${"a": "No decision-maker is never wrong.", "c": "Avoiding decisions is avoiding the role.", "d": "Ownership means not deflecting."}$$,
   $$medium$$),
  (16, $$Learning to say no / push back well (from earlier lessons) matters for the PM path because:$$,
   $$[{"id": "a", "text": "PMs never say no"}, {"id": "b", "text": "Owning outcomes means protecting scope, schedule, and the team — which requires principled push-back, not just compliance"}, {"id": "c", "text": "It makes you popular"}, {"id": "d", "text": "It avoids all conflict"}]$$,
   $$b$$,
   $${"a": "PMs must say no with judgement.", "c": "It's about protecting the project, not popularity.", "d": "It involves handling conflict, not avoiding it."}$$,
   $$medium$$),
  (17, $$The chapter suggests reflecting on decisions after the fact to:$$,
   $$[{"id": "a", "text": "Assign blame"}, {"id": "b", "text": "Learn — asking what you'd do differently and why, so each project compounds your judgement"}, {"id": "c", "text": "Prove you were right"}, {"id": "d", "text": "Document for HR"}]$$,
   $$b$$,
   $${"a": "Reflection is for learning, not blame.", "c": "It's about growth, not vindication.", "d": "It's personal development, not a record-keeping task."}$$,
   $$medium$$),
  (18, $$Broadening from your own tasks to the whole project means a future PM should understand:$$,
   $$[{"id": "a", "text": "Only their immediate deliverables"}, {"id": "b", "text": "How the parts fit — the business case, stakeholders, risks, and trade-offs, not just the task list"}, {"id": "c", "text": "Only the schedule"}, {"id": "d", "text": "Only the budget"}]$$,
   $$b$$,
   $${"a": "PM scope is the whole project.", "c": "More than the schedule.", "d": "More than the budget."}$$,
   $$medium$$),
  (19, $$Mentorship and sponsorship differ in that:$$,
   $$[{"id": "a", "text": "They are identical"}, {"id": "b", "text": "A mentor advises you; a sponsor advocates for you when opportunities and decisions are being made — you benefit from both"}, {"id": "c", "text": "Only mentorship matters"}, {"id": "d", "text": "Only sponsorship matters"}]$$,
   $$b$$,
   $${"a": "They play different roles.", "c": "Sponsorship opens doors mentorship alone can't.", "d": "Mentorship builds the skill sponsorship advocates for."}$$,
   $$hard$$),
  (20, $$The chapter's closing principle on the coordinator-to-PM path is:$$,
   $$[{"id": "a", "text": "Wait to be chosen"}, {"id": "b", "text": "Grow into the role deliberately — practise judgement, take ownership early, build a visible track record, and the step up follows readiness"}, {"id": "c", "text": "The title makes the manager"}, {"id": "d", "text": "Coordination skills become useless as a PM"}]$$,
   $$b$$,
   $${"a": "You prepare actively rather than wait.", "c": "Readiness makes the manager; the title recognises it.", "d": "Those skills are the foundation you build on."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'coordinator-to-pm'
on conflict do nothing;
