-- Seed 20 quiz items for Lesson 15 (dashboards). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'dashboards');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'dashboard_literacy', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$The 'beautiful and useless' award-winning dashboard failed because:$$,
   $$[{"id": "a", "text": "Its metrics were inaccurate"}, {"id": "b", "text": "Every metric was accurate, but it told the story management wanted — not whether the program would actually succeed"}, {"id": "c", "text": "It wasn't updated often enough"}, {"id": "d", "text": "It used too few colours"}]$$,
   $$b$$,
   $${"a": "Every metric was technically accurate — that was the trap.", "c": "It was updated daily; freshness wasn't the problem.", "d": "It had four colours and eleven visualisations."}$$,
   $$medium$$),
  (2, $$Milestones showing ~90% complete were misleading because:$$,
   $$[{"id": "a", "text": "The percentage was miscalculated"}, {"id": "b", "text": "Milestones were defined broadly — slipping one hard one (integration go-live) while hitting ten easy ones still read ~90%"}, {"id": "c", "text": "The milestones were all complete"}, {"id": "d", "text": "There were no milestones"}]$$,
   $$b$$,
   $${"a": "The maths was right; the definition was the issue.", "c": "A hard one had slipped.", "d": "There were many — too broadly defined."}$$,
   $$medium$$),
  (3, $$'Hours burned tracking to plan' concealed:$$,
   $$[{"id": "a", "text": "That the team was idle"}, {"id": "b", "text": "That disproportionate time was going to rework, recorded the same way as greenfield work"}, {"id": "c", "text": "That the budget had doubled"}, {"id": "d", "text": "Nothing — it was a healthy metric"}]$$,
   $$b$$,
   $${"a": "The team was busy — on rework.", "c": "Hours tracked close to plan; the composition was the problem.", "d": "It hid the rework signal."}$$,
   $$medium$$),
  (4, $$A stable count of ~20 open risks hid:$$,
   $$[{"id": "a", "text": "Nothing — stability is good"}, {"id": "b", "text": "A deteriorating composition — closed risks were easy ones; remaining risks were concentrated on the critical path"}, {"id": "c", "text": "That all risks were closed"}, {"id": "d", "text": "A budget overrun"}]$$,
   $$b$$,
   $${"a": "A stable total can mask a worsening profile.", "c": "Twenty remained open.", "d": "It hid a risk-profile shift, not budget."}$$,
   $$medium$$),
  (5, $$The defect count trending downward actually reflected:$$,
   $$[{"id": "a", "text": "Defects being fixed faster"}, {"id": "b", "text": "Testing slowing down — fewer tests run means fewer defects found"}, {"id": "c", "text": "Better code"}, {"id": "d", "text": "More testers added"}]$$,
   $$b$$,
   $${"a": "It looked like that but wasn't.", "c": "Quality wasn't improving; testing was shrinking.", "d": "Fewer tests were being run, not more."}$$,
   $$medium$$),
  (6, $$The chapter's core claim about dashboards is:$$,
   $$[{"id": "a", "text": "A dashboard is a neutral mirror of the project"}, {"id": "b", "text": "A dashboard is a choice about what matters, and every choice excludes something"}, {"id": "c", "text": "More metrics always mean more insight"}, {"id": "d", "text": "Dashboards should always be green"}]$$,
   $$b$$,
   $${"a": "Dashboards are not neutral.", "c": "Clutter obscures signal.", "d": "Always-green is the lie-by-omission failure."}$$,
   $$medium$$),
  (7, $$A good dashboard answers four questions at a glance. Which set?$$,
   $$[{"id": "a", "text": "Who, what, where, when"}, {"id": "b", "text": "Are we on track to objectives; where is the pressure; what has changed since last time; what needs senior attention"}, {"id": "c", "text": "How many bars, colours, metrics, and pages"}, {"id": "d", "text": "Scope, schedule, cost, quality"}]$$,
   $$b$$,
   $${"a": "Generic questions, not the dashboard's four.", "c": "Presentation, not insight.", "d": "Project variables, not the dashboard's four questions."}$$,
   $$medium$$),
  (8, $$'Where is the pressure?' is best shown as:$$,
   $$[{"id": "a", "text": "'There are twenty open risks'"}, {"id": "b", "text": "'These three risks are currently most consequential'"}, {"id": "c", "text": "A total defect count"}, {"id": "d", "text": "Hours burned to date"}]$$,
   $$b$$,
   $${"a": "A raw count doesn't show where the pressure is.", "c": "A total hides which items matter.", "d": "That's an activity metric, not pressure."}$$,
   $$medium$$),
  (9, $$Which is an OUTCOME metric rather than an activity metric?$$,
   $$[{"id": "a", "text": "Hours burned"}, {"id": "b", "text": "Features accepted by the product owner"}, {"id": "c", "text": "Meetings held"}, {"id": "d", "text": "Emails sent"}]$$,
   $$b$$,
   $${"a": "Hours burned shows busyness, not value.", "c": "Meetings held is activity; decisions made would be the outcome.", "d": "Activity, not outcome."}$$,
   $$medium$$),
  (10, $$Which is a LEADING indicator?$$,
   $$[{"id": "a", "text": "Defect count (after testing finds problems)"}, {"id": "b", "text": "Code-review coverage (tells you about quality practices before problems surface)"}, {"id": "c", "text": "Final acceptance sign-off"}, {"id": "d", "text": "Post-go-live incident count"}]$$,
   $$b$$,
   $${"a": "Defect count is lagging — it's history.", "c": "Sign-off is a lagging, end-state measure.", "d": "Incidents are lagging."}$$,
   $$medium$$),
  (11, $$'Track composition, not just totals' means preferring:$$,
   $$[{"id": "a", "text": "'Twenty open risks'"}, {"id": "b", "text": "'Three critical-path risks, five medium, twelve low' — the composition is where the signal lives"}, {"id": "c", "text": "A single risk score"}, {"id": "d", "text": "No risk reporting"}]$$,
   $$b$$,
   $${"a": "A total hides the profile.", "c": "One number collapses the composition.", "d": "Risks must be reported, just in a useful shape."}$$,
   $$medium$$),
  (12, $$Why track trend, not just point values?$$,
   $$[{"id": "a", "text": "Trends look impressive"}, {"id": "b", "text": "A point value can't be interpreted alone — is 87% good? Depends whether it was 92% or 81% last week"}, {"id": "c", "text": "Point values are always wrong"}, {"id": "d", "text": "Trends replace the need for targets"}]$$,
   $$b$$,
   $${"a": "It's about interpretability, not aesthetics.", "c": "Point values aren't wrong, just uninterpretable alone.", "d": "Trends complement targets, not replace them."}$$,
   $$medium$$),
  (13, $$A metric that has sat on the dashboard for three months with no one ever asking about it should be:$$,
   $$[{"id": "a", "text": "Kept for completeness"}, {"id": "b", "text": "Removed — it's noise; dashboards accumulate metrics and rarely subtract them"}, {"id": "c", "text": "Made larger"}, {"id": "d", "text": "Moved to the executive view"}]$$,
   $$b$$,
   $${"a": "Completeness for its own sake creates clutter.", "c": "Emphasising noise doesn't help.", "d": "Moving noise elsewhere doesn't remove it."}$$,
   $$medium$$),
  (14, $$A dashboard that is all-green for twelve weeks is:$$,
   $$[{"id": "a", "text": "Evidence of excellent delivery"}, {"id": "b", "text": "Reporting a lie by omission — the test is whether the rating changes ever reflect anything"}, {"id": "c", "text": "Required by governance"}, {"id": "d", "text": "Fine if the metrics are accurate"}]$$,
   $$b$$,
   $${"a": "Persistent green is suspicious, not proof of excellence.", "c": "Governance wants honesty, not perpetual green.", "d": "Accurate-but-always-green still misleads."}$$,
   $$medium$$),
  (15, $$Color-by-threshold automation can be gamed because:$$,
   $$[{"id": "a", "text": "Colours fade over time"}, {"id": "b", "text": "Thresholds drift toward whatever the current number is; the complement is a PM judgment override with written rationale"}, {"id": "c", "text": "It's too objective"}, {"id": "d", "text": "It can't use red"}]$$,
   $$b$$,
   $${"a": "It's about threshold-drift, not display fading.", "c": "The gaming makes it less objective, not too objective.", "d": "It can use any RAG colour."}$$,
   $$hard$$),
  (16, $$The three dashboard layers are:$$,
   $$[{"id": "a", "text": "Daily, weekly, monthly"}, {"id": "b", "text": "Team (operational), project (tactical), executive (strategic) — each tailored to its audience"}, {"id": "c", "text": "Red, amber, green"}, {"id": "d", "text": "Past, present, future"}]$$,
   $$b$$,
   $${"a": "Those are cadences, not audiences.", "c": "Those are RAG colours.", "d": "Those are timeframes."}$$,
   $$medium$$),
  (17, $$Most dashboard failures come from:$$,
   $$[{"id": "a", "text": "Too few metrics"}, {"id": "b", "text": "Trying to serve all three audiences with one view — too detailed for the sponsor, too thin for the team"}, {"id": "c", "text": "Updating too frequently"}, {"id": "d", "text": "Using standard colours"}]$$,
   $$b$$,
   $${"a": "Too many, undifferentiated, is the usual problem.", "c": "Frequency isn't the core failure.", "d": "Standard colours are recommended."}$$,
   $$medium$$),
  (18, $$'Verify what you publish' means that when a lead reports 80% complete, you:$$,
   $$[{"id": "a", "text": "Publish it as-is"}, {"id": "b", "text": "Check whether the burn-up and the accepted deliverables reconcile; confirm a 'closed' risk is actually closed, not just set aside"}, {"id": "c", "text": "Round it to 100%"}, {"id": "d", "text": "Wait for the sponsor to verify"}]$$,
   $$b$$,
   $${"a": "Publishing unverified inputs is how dashboards lie.", "c": "Rounding up is exactly the soft-number problem.", "d": "Verification is the coordinator's job, not the sponsor's."}$$,
   $$medium$$),
  (19, $$'Do not hide behind the dashboard' means that when a senior person asks a question the dashboard doesn't answer, you:$$,
   $$[{"id": "a", "text": "Point at the dashboard and move on"}, {"id": "b", "text": "Answer the question directly, and note whether the dashboard could be improved to cover it next time"}, {"id": "c", "text": "Say the data isn't available"}, {"id": "d", "text": "Refer them to the PM only"}]$$,
   $$b$$,
   $${"a": "Pointing at the dashboard dodges the question.", "c": "You answer from your operational knowledge.", "d": "You can answer; improve the dashboard afterward."}$$,
   $$medium$$),
  (20, $$The chapter says the best (honest) dashboards:$$,
   $$[{"id": "a", "text": "Are always green and reassuring"}, {"id": "b", "text": "Look slightly uncomfortable — they show amber/red where they belong; that honesty is what makes the green trusted when it appears"}, {"id": "c", "text": "Have the most visualisations"}, {"id": "d", "text": "Never change colour"}]$$,
   $$b$$,
   $${"a": "Always-green dashboards get discounted over time.", "c": "Quantity of charts isn't honesty.", "d": "Honest ratings change to reflect reality."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'dashboards'
on conflict do nothing;
