-- Seed 20 quiz items for Lesson 9 (wbs / Ch 9). Hand-authored, grounded in Chapter 9.
-- Idempotent: clears this lesson's items first.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'wbs');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'wbs_discipline', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$The chapter argues a WBS is fundamentally:$$,
   $$[{"id":"a","text":"A diagram you produce for the plan"},{"id":"b","text":"A shared model of the work, built by the people who will do it — the diagram is just the residue"},{"id":"c","text":"A flat list of every task on the project"},{"id":"d","text":"A schedule with dates and dependencies"}]$$,
   $$b$$,
   $${"a":"The diagram is the residue; the shared model is the point.","c":"That's a task list — a WBS is a structured decomposition, not a flat list.","d":"That's the schedule; the WBS is the 'what', the schedule is the 'when'."}$$,
   $$medium$$),
  (2, $$The 100% rule states that:$$,
   $$[{"id":"a","text":"The project must be 100% complete before closure"},{"id":"b","text":"The work captured at any level must represent 100% of the work needed at that level — no more, no less"},{"id":"c","text":"100% of packages must be 8–80 hours"},{"id":"d","text":"Every package must be 100% assigned before kickoff"}]$$,
   $$b$$,
   $${"a":"It's about scope completeness of the decomposition, not project completion.","c":"That's the 8/80 sizing rule, a different principle.","d":"Assignment is the RAM's job; the 100% rule is about capturing all the work."}$$,
   $$easy$$),
  (3, $$'No less' (the most common WBS failure) usually means omitting:$$,
   $$[{"id":"a","text":"Out-of-scope work"},{"id":"b","text":"Project-management overhead, change management, training, documentation, transition, and closure"},{"id":"c","text":"The project outcome statement"},{"id":"d","text":"The numbering scheme"}]$$,
   $$b$$,
   $${"a":"That's a 'no more' violation (including out-of-scope work).","c":"The outcome is the top of the WBS, rarely the thing omitted.","d":"Numbering is cleanup, not a category of work that gets forgotten."}$$,
   $$medium$$),
  (4, $$How does a WBS differ from a task list?$$,
   $$[{"id":"a","text":"There is no difference"},{"id":"b","text":"A WBS is a structured decomposition answering 'what does this project consist of' at multiple levels; a task list is a flat enumeration"},{"id":"c","text":"A task list is more rigorous"},{"id":"d","text":"A WBS includes dates; a task list does not"}]$$,
   $$b$$,
   $${"a":"They're genuinely different artifacts.","c":"The WBS's structure is what gives it rigour the flat list lacks.","d":"Dates belong to the schedule, not the WBS."}$$,
   $$medium$$),
  (5, $$The WBS is the project's ___, and the schedule is the ___:$$,
   $$[{"id":"a","text":"when; what"},{"id":"b","text":"what; when"},{"id":"c","text":"who; why"},{"id":"d","text":"cost; risk"}]$$,
   $$b$$,
   $${"a":"Reversed — the WBS is the what, the schedule the when.","c":"Those are the RAM and business-case, not WBS vs schedule.","d":"Cost and risk are downstream artifacts the WBS feeds."}$$,
   $$easy$$),
  (6, $$The 8/80 rule of thumb says a work package should be:$$,
   $$[{"id":"a","text":"8 to 80 days long"},{"id":"b","text":"Between 8 and 80 person-hours of work"},{"id":"c","text":"Decomposed into 8 to 80 sub-tasks"},{"id":"d","text":"Owned by 8 to 80 people"}]$$,
   $$b$$,
   $${"a":"It's person-hours, not days.","c":"It's about the size of the package, not a count of sub-tasks.","d":"Each package should have exactly one accountable owner."}$$,
   $$medium$$),
  (7, $$The chapter says to decompose the WBS by:$$,
   $$[{"id":"a","text":"Activity, not deliverable"},{"id":"b","text":"Deliverable, not activity"},{"id":"c","text":"Calendar month"},{"id":"d","text":"Individual person"}]$$,
   $$b$$,
   $${"a":"Reversed — activities belong in the schedule, deliverables in the WBS.","c":"Time-based grouping is the schedule's job.","d":"You decompose by the work produced; assignment comes after."}$$,
   $$medium$$),
  (8, $$Which is a deliverable (WBS) rather than an activity (schedule)?$$,
   $$[{"id":"a","text":"Meet with the vendor"},{"id":"b","text":"Write the integration specifications"},{"id":"c","text":"Build integration"},{"id":"d","text":"Review the drafts"}]$$,
   $$c$$,
   $${"a":"That's an activity — an action the team takes.","b":"That's an activity producing part of a deliverable.","d":"That's an activity, not the thing produced."}$$,
   $$medium$$),
  (9, $$One WBS branch is decomposed to five levels and another to two. This most likely signals:$$,
   $$[{"id":"a","text":"A perfectly balanced plan"},{"id":"b","text":"Uneven planning — one area is understood much better than the other (it may be legitimate, but should be deliberate)"},{"id":"c","text":"That the deeper branch is out of scope"},{"id":"d","text":"That the shallow branch should be deleted"}]$$,
   $$b$$,
   $${"a":"Inconsistent depth is the opposite of balanced.","c":"Depth doesn't indicate scope membership.","d":"Shallow may just mean less-understood work, not deletable work."}$$,
   $$medium$$),
  (10, $$When should you stop decomposing a branch of the WBS?$$,
   $$[{"id":"a","text":"When every hour of work is described"},{"id":"b","text":"When further decomposition would not help you plan — the package is small enough to estimate and assign"},{"id":"c","text":"At exactly four levels, always"},{"id":"d","text":"Never — more detail is always better"}]$$,
   $$b$$,
   $${"a":"You're not describing every hour; you're enabling planning.","c":"Levels vary by project; there's no fixed depth.","d":"Over-decomposition turns tasks into rituals."}$$,
   $$medium$$),
  (11, $$In the chapter's branch-rationalisation story, the main benefit of building the WBS in a workshop rather than alone was:$$,
   $$[{"id":"a","text":"It was faster than solo drafting"},{"id":"b","text":"The team caught omissions AND believed in it — nobody later said 'that's not what I signed up for'"},{"id":"c","text":"It produced a prettier diagram"},{"id":"d","text":"It avoided needing a PM"}]$$,
   $$b$$,
   $${"a":"It was slower — but better, because of shared ownership.","c":"The value was the shared model, not the visuals.","d":"The PM (Tom) facilitated it; it didn't remove the PM."}$$,
   $$medium$$),
  (12, $$What are the coordinator's three specific jobs in a WBS workshop?$$,
   $$[{"id":"a","text":"Estimate, schedule, and assign every package"},{"id":"b","text":"Capture the WBS accurately/visibly, surface the forgotten categories of work, and track decisions/dependencies that emerge"},{"id":"c","text":"Decide the project outcome and the budget"},{"id":"d","text":"Facilitate the session and overrule the team"}]$$,
   $$b$$,
   $${"a":"Estimating/scheduling come later; the workshop captures the 'what'.","c":"The outcome is set with the team; the budget is downstream.","d":"The PM facilitates; the coordinator captures and surfaces, not overrules."}$$,
   $$medium$$),
  (13, $$The top level of a WBS is usually:$$,
   $$[{"id":"a","text":"Individual work packages"},{"id":"b","text":"The project outcome — a single concrete statement of what the project will produce"},{"id":"c","text":"The list of activities"},{"id":"d","text":"The risk register"}]$$,
   $$b$$,
   $${"a":"Packages are the leaves at the bottom, not the top.","c":"Activities aren't in the WBS at all.","d":"The risk register is a downstream artifact fed by the WBS."}$$,
   $$easy$$),
  (14, $$How many accountable owners should each work package have?$$,
   $$[{"id":"a","text":"As many as are involved"},{"id":"b","text":"Exactly one"},{"id":"c","text":"None — ownership is collective"},{"id":"d","text":"One per level of the hierarchy"}]$$,
   $$b$$,
   $${"a":"Multiple accountable parties means no one is actually accountable.","c":"Collective ownership is diffuse ownership.","d":"Accountability sits at the package, singular."}$$,
   $$medium$$),
  (15, $$A good way to build the risk register from the WBS is to:$$,
   $$[{"id":"a","text":"Copy risks from a generic template"},{"id":"b","text":"Walk the WBS and ask, at each leaf, 'what could go wrong here?'"},{"id":"c","text":"Wait until a risk materialises"},{"id":"d","text":"Ask only the sponsor"}]$$,
   $$b$$,
   $${"a":"A generic template misses the project's actual uncertainty.","c":"That's reactive, not a register built from the work.","d":"The people doing each package see its risks best, not just the sponsor."}$$,
   $$medium$$),
  (16, $$Why does the chapter stress catching omissions at WBS build-time?$$,
   $$[{"id":"a","text":"Because errors in the WBS propagate — a missing package becomes missing schedule activities, missing budget, and missing status tracking"},{"id":"b","text":"Because the WBS is never changed after baseline"},{"id":"c","text":"Because stakeholders only read the WBS"},{"id":"d","text":"Because it is required for sign-off"}]$$,
   $$a$$,
   $${"b":"It does evolve via change requests; build-time still matters because errors compound.","c":"Many artifacts derive from it, not just stakeholder reading.","d":"The reason is downstream propagation, not a sign-off formality."}$$,
   $$medium$$),
  (17, $$A package that has been 'in progress' far longer than its estimate suggests usually means:$$,
   $$[{"id":"a","text":"The team is lazy"},{"id":"b","text":"The package should have been decomposed further — it was hiding too much variability"},{"id":"c","text":"The 100% rule was violated"},{"id":"d","text":"The schedule is wrong but the WBS is fine"}]$$,
   $$b$$,
   $${"a":"The chapter reads it as a sizing signal, not a people judgement.","c":"That's about scope completeness, not package size.","d":"The signal points back to the WBS package being too large."}$$,
   $$medium$$),
  (18, $$When a change request adds scope, what must happen to the WBS?$$,
   $$[{"id":"a","text":"Nothing — the WBS is frozen after baseline"},{"id":"b","text":"It must be updated, or the official scope (WBS) will differ from reality (what the team is building)"},{"id":"c","text":"It should be rebuilt from scratch"},{"id":"d","text":"Only the schedule needs updating"}]$$,
   $$b$$,
   $${"a":"It evolves through controlled change, not a freeze.","c":"You update it, not rebuild it wholesale.","d":"Updating only the schedule leaves the scope record wrong."}$$,
   $$medium$$),
  (19, $$'The diagram is the residue. The model is the point.' means:$$,
   $$[{"id":"a","text":"You don't need to capture the WBS at all"},{"id":"b","text":"The real value is the shared mental model of the work the team builds together; the artifact is just its record"},{"id":"c","text":"Diagrams are unprofessional"},{"id":"d","text":"The PM should draw it alone"}]$$,
   $$b$$,
   $${"a":"You do capture it — the diagram is the evidence of the model.","c":"Nothing about professionalism; it's about where the value sits.","d":"The opposite — the model is built collaboratively."}$$,
   $$medium$$),
  (20, $$'Decompose by who will do the work' means:$$,
   $$[{"id":"a","text":"Name a person in every package title"},{"id":"b","text":"Two pieces done by completely different teams/skills/timelines should be separate packages; same-team single-flow work may be combined"},{"id":"c","text":"Only managers get packages"},{"id":"d","text":"Decompose strictly by org chart"}]$$,
   $$b$$,
   $${"a":"It's about making assignment clean, not putting names in titles.","c":"Anyone who owns work can own a package.","d":"It's about the flow of work, which doesn't always match the org chart."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'wbs'
on conflict do nothing;
