-- Seed 20 quiz items for Lesson 8 (requirements-literacy / Ch 8).
-- Hand-authored (is_ai_generated = false), grounded in handbook Chapter 8.
-- Format matches existing quiz_items: options [{id,text}], correct=id,
-- distractor_rationale {wrong_id: why-wrong}, competency, difficulty.
-- Idempotent: clears this lesson's items first (matches the app's replace pattern).

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'requirements-literacy');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'requirements_literacy', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$The chapter's "daily claims reporting" story is a case study in which requirements failure mode?$$,
   $$[{"id":"a","text":"Incompleteness — the requirement left out error handling"},{"id":"b","text":"Ambiguity — the same words meant different things to different teams"},{"id":"c","text":"Conflict — two requirements that could not both be met"},{"id":"d","text":"Scope creep — a new requirement was added late"}]$$,
   $$b$$,
   $${"a":"The problem wasn't missing edge cases; it was that 'daily' itself carried two readings.","c":"There was no conflict between two requirements — one requirement was read two ways.","d":"Nothing was added; an existing requirement was understood differently by two groups."}$$,
   $$easy$$),
  (2, $$After the 'daily' incident, the PM told the coordinator that surfacing the signal they noticed was:$$,
   $$[{"id":"a","text":"Overstepping — requirements are the BA's domain"},{"id":"b","text":"Doing your job — noticing and surfacing the signal is part of the coordinator's quality control"},{"id":"c","text":"Acceptable only because it turned out to be right"},{"id":"d","text":"Something to raise only with the senior stakeholder, not the BA"}]$$,
   $$b$$,
   $${"a":"The PM's exact point was the opposite — surfacing the signal is not interfering with the BA.","c":"The duty to surface exists regardless of how it turns out; it's about noticing the signal.","d":"The recommended move is a short note to the BA, not routing around them."}$$,
   $$medium$$),
  (3, $$The chapter frames requirements as 'a bet.' What does that framing change about how you read them?$$,
   $$[{"id":"a","text":"You read them as a fixed contract that cannot be questioned"},{"id":"b","text":"You read them as a hypothesis about what will be valuable, staying alert for drift from reality"},{"id":"c","text":"You ignore them because they are always partly wrong"},{"id":"d","text":"You treat them as solely the analyst's concern"}]$$,
   $$b$$,
   $${"a":"The bet framing is explicitly the opposite of an unquestionable contract.","c":"Being partly wrong is why you watch them, not why you ignore them.","d":"The chapter argues requirements are everyone's domain, including the coordinator's."}$$,
   $$medium$$),
  (4, $$Which of these is a NON-functional requirement?$$,
   $$[{"id":"a","text":"The system shall allow users to reset their passwords"},{"id":"b","text":"The system shall respond to user input within 200 milliseconds"},{"id":"c","text":"Reduce average claims processing time by 30%"},{"id":"d","text":"Claims processors need to search by policy number and date range"}]$$,
   $$b$$,
   $${"a":"That describes what the system does — a functional requirement.","c":"That's a business requirement (an objective / the 'why').","d":"That's a user requirement (what a specific user group needs)."}$$,
   $$easy$$),
  (5, $$'Provide a single view of customer across three divisions' is best classified as which type of requirement?$$,
   $$[{"id":"a","text":"Functional"},{"id":"b","text":"Non-functional"},{"id":"c","text":"Business"},{"id":"d","text":"Data"}]$$,
   $$c$$,
   $${"a":"It states an organisational objective, not a specific system function.","b":"It isn't a quality attribute like performance or security.","d":"It's about a business outcome, not a specification of data format or handling."}$$,
   $$medium$$),
  (6, $$Why does the chapter call words like 'user-friendly,' 'robust,' and 'seamless' landmines?$$,
   $$[{"id":"a","text":"They are too technical for stakeholders"},{"id":"b","text":"They seem precise but have no measurable threshold — ask what specific threshold is meant"},{"id":"c","text":"They belong only in the non-functional section"},{"id":"d","text":"They are always signs of scope creep"}]$$,
   $$b$$,
   $${"a":"The issue is vagueness, not that they're too technical.","c":"The problem isn't placement; it's that they aren't testable as written.","d":"They signal ambiguity, not necessarily added scope."}$$,
   $$medium$$),
  (7, $$'The system shall allow users to upload documents' — with nothing about file size, type, or what happens if the upload fails — is an example of:$$,
   $$[{"id":"a","text":"Ambiguity"},{"id":"b","text":"Incompleteness"},{"id":"c","text":"Conflict"},{"id":"d","text":"A solution in disguise"}]$$,
   $$b$$,
   $${"a":"The words are clear; what's missing are the edge cases and exceptions.","c":"It doesn't contradict another requirement.","d":"It states a need, not a pre-chosen solution."}$$,
   $$medium$$),
  (8, $$'Reports within 5 seconds' AND 'the daily report includes all of the previous month's transactions' may, at high data volume, be an example of:$$,
   $$[{"id":"a","text":"Unstated assumption"},{"id":"b","text":"Conflict — two requirements that cannot both be met"},{"id":"c","text":"Wrong level of abstraction"},{"id":"d","text":"A regulatory requirement"}]$$,
   $$b$$,
   $${"a":"The tension is between two stated requirements, not a hidden assumption.","c":"Both are at a reasonable level; the issue is they collide.","d":"Neither is imposed by law or regulation."}$$,
   $$medium$$),
  (9, $$A requirement that reads 'the login button shall be blue, 16x40 pixels, in the top-right corner' suffers from:$$,
   $$[{"id":"a","text":"Being too specific — prescribing implementation detail that should be left to designers"},{"id":"b","text":"Being too vague to build from"},{"id":"c","text":"Being non-functional"},{"id":"d","text":"Being untestable"}]$$,
   $$a$$,
   $${"b":"It's the opposite problem — over-specified, not vague.","c":"It describes a function/appearance, not a quality attribute.","d":"It's very testable; the problem is it over-constrains the solution."}$$,
   $$medium$$),
  (10, $$A stakeholder says 'we need a new field on the claim form for region code.' Why does the chapter treat this with caution?$$,
   $$[{"id":"a","text":"It is too vague to act on"},{"id":"b","text":"It is a solution in disguise — the underlying need (segmenting claims by region) might be met another way"},{"id":"c","text":"It is a non-functional requirement"},{"id":"d","text":"It is a regulatory constraint"}]$$,
   $$b$$,
   $${"a":"It's quite specific — that's part of the trap.","c":"It describes functionality, but the deeper issue is it pre-commits a solution.","d":"There's no legal/regulatory constraint stated."}$$,
   $$hard$$),
  (11, $$The chapter recommends reading a requirements document in how many passes, and to what end?$$,
   $$[{"id":"a","text":"One pass, to find your name in the RACI"},{"id":"b","text":"Three passes — structural, substantive, and critical"},{"id":"c","text":"Only the sections you personally own"},{"id":"d","text":"None — trust the BA's sign-off"}]$$,
   $$b$$,
   $${"a":"That's exactly the inadequate approach the chapter warns against.","c":"Scope management depends on understanding the whole document, not just your sections.","d":"The sign-off is precisely why ambiguities go uncaught — read it yourself."}$$,
   $$easy$$),
  (12, $$On the critical (third) pass, what should the coordinator produce?$$,
   $$[{"id":"a","text":"A full re-analysis of every requirement"},{"id":"b","text":"A short list (roughly 5–10) of watchpoints — the ambiguities and failure modes that stood out"},{"id":"c","text":"A formal sign-off"},{"id":"d","text":"Nothing — just absorb it"}]$$,
   $$b$$,
   $${"a":"That's the BA's job; the coordinator keeps a short watchlist.","c":"The pass produces watchpoints, not approval.","d":"The point is to capture the watchpoints you'll track during the build."}$$,
   $$medium$$),
  (13, $$You spot an ambiguity on requirement 4.3.7 ('daily reporting'). The chapter's recommended move is:$$,
   $$[{"id":"a","text":"Rewrite the requirement yourself"},{"id":"b","text":"Send a short two-minute note to the BA asking which reading is intended"},{"id":"c","text":"Escalate it straight to the sponsor"},{"id":"d","text":"Leave it — requirements are the BA's job"}]$$,
   $$b$$,
   $${"a":"Rewriting it is the BA's call; you flag it for confirmation.","c":"A two-minute note to the BA is the proportionate first move, not a sponsor escalation.","d":"Noticing and surfacing is doing your job — silence is what caused the 'daily' failure."}$$,
   $$easy$$),
  (14, $$Good traceability lets a project reliably answer which kind of question?$$,
   $$[{"id":"a","text":"How many defects are currently open"},{"id":"b","text":"Why are we building this, and if we cut feature X, which business objective is no longer met"},{"id":"c","text":"Who on the team is on leave next week"},{"id":"d","text":"What the team's velocity was last sprint"}]$$,
   $$b$$,
   $${"a":"Defect counts come from test tracking, not the traceability of requirements to objectives.","c":"That's resourcing, unrelated to requirement traceability.","d":"Velocity is a delivery metric, not a traceability question."}$$,
   $$medium$$),
  (15, $$What level of detail does the chapter recommend for maintaining traceability?$$,
   $$[{"id":"a","text":"Every single atomic requirement, no matter how many"},{"id":"b","text":"At the level of requirement groups or user stories — meaningful chunks, not every bullet"},{"id":"c","text":"Only regulatory requirements"},{"id":"d","text":"Don't maintain it — it's pure paperwork"}]$$,
   $$b$$,
   $${"a":"A 3,000-row matrix can't be maintained meaningfully; aim for meaningful chunks.","c":"All requirement types benefit from traceability, not just regulatory ones.","d":"Done at the right level it's one of the highest-impact things a coordinator can do."}$$,
   $$medium$$),
  (16, $$A requirement exists in the document but cannot be traced to any business objective or stakeholder. What should you do?$$,
   $$[{"id":"a","text":"Delete it immediately"},{"id":"b","text":"Flag it as a signal/risk — it may be scope that needn't be there, or broken traceability"},{"id":"c","text":"Assume it must be important and leave it"},{"id":"d","text":"Ignore it; untraceable items are normal"}]$$,
   $$b$$,
   $${"a":"Don't unilaterally cut it; surface it so the team can decide deliberately.","c":"An orphaned requirement is exactly what shouldn't be assumed important.","d":"It's a signal worth surfacing, not normal background."}$$,
   $$medium$$),
  (17, $$How do requirements relate to the WBS?$$,
   $$[{"id":"a","text":"They are unrelated artifacts"},{"id":"b","text":"WBS work that doesn't trace to a requirement is either labelled overhead or surfaced as possible scope creep"},{"id":"c","text":"Every WBS item is scope creep"},{"id":"d","text":"Requirements are derived from the WBS"}]$$,
   $$b$$,
   $${"a":"The WBS decomposes the work needed to deliver the requirements — tightly related.","c":"Plenty of WBS work is legitimate overhead; the point is to label or surface untraced work.","d":"It's the other direction — requirements drive the WBS."}$$,
   $$medium$$),
  (18, $$In Scrum, where do requirements primarily live?$$,
   $$[{"id":"a","text":"In a classical traceability matrix"},{"id":"b","text":"In the product backlog, as user stories with acceptance criteria"},{"id":"c","text":"In a signed-off requirements document only"},{"id":"d","text":"In the RAID log"}]$$,
   $$b$$,
   $${"a":"In agile, the backlog structure IS the traceability; a classical matrix isn't maintained.","c":"That's the classical, relatively-stable approach — agile expects the backlog to evolve.","d":"The RAID log tracks risks/issues, not the requirement set."}$$,
   $$easy$$),
  (19, $$What makes a requirement 'testable,' per the chapter?$$,
   $$[{"id":"a","text":"It uses the word 'shall'"},{"id":"b","text":"You can describe how you would verify it is met (e.g. loads the dashboard within 2s under 10 concurrent users)"},{"id":"c","text":"It is short"},{"id":"d","text":"It names a specific technology"}]$$,
   $$b$$,
   $${"a":"The 'shall' form is a style convention, not what makes it verifiable.","c":"Length is irrelevant; verifiability is the test.","d":"Naming a technology is often a constraint, not what makes a requirement testable."}$$,
   $$medium$$),
  (20, $$'The system shall use Oracle 19c' is often, in truth, a:$$,
   $$[{"id":"a","text":"Business requirement"},{"id":"b","text":"Constraint (organisational — existing licence/expertise) that should be flagged so it isn't traded away under pressure"},{"id":"c","text":"User requirement"},{"id":"d","text":"Stakeholder dream/wish"}]$$,
   $$b$$,
   $${"a":"It isn't an objective; it's an imposed technical constraint.","c":"No user group's need is expressed here.","d":"It's the opposite of an aspirational wish — it's an immovable constraint."}$$,
   $$hard$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'requirements-literacy'
on conflict do nothing;
