-- Seed 20 quiz items for Lesson 21 (stakeholder-relationships). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'stakeholder-relationships');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'relationship_stewardship', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$The chapter frames stakeholder relationships as:$$,
   $$[{"id": "a", "text": "A soft, optional nicety"}, {"id": "b", "text": "A real project asset that the coordinator is often the day-to-day steward of"}, {"id": "c", "text": "The PM's job alone, not the coordinator's"}, {"id": "d", "text": "Something to manage only when problems arise"}]$$,
   $$b$$,
   $${"a": "The chapter treats relationships as a core asset, not a nicety.", "c": "The coordinator is frequently the day-to-day steward.", "d": "Stewardship is continuous, not reactive."}$$,
   $$medium$$),
  (2, $$The 'trust account' metaphor describes:$$,
   $$[{"id": "a", "text": "A literal budget line"}, {"id": "b", "text": "A balance built by deposits (reliable acts) and drawn down by withdrawals (broken commitments, surprises, sloppiness)"}, {"id": "c", "text": "The project's contingency reserve"}, {"id": "d", "text": "A stakeholder's formal authority"}]$$,
   $$b$$,
   $${"a": "It's a relationship metaphor, not a finance line.", "c": "That's schedule/cost contingency.", "d": "Authority is positional; trust is earned."}$$,
   $$medium$$),
  (3, $$The single largest source of trust deposits is:$$,
   $$[{"id": "a", "text": "Occasional grand gestures"}, {"id": "b", "text": "Reliably doing the small things you said you'd do, consistently over time"}, {"id": "c", "text": "Agreeing with everyone"}, {"id": "d", "text": "Being the most senior person in the room"}]$$,
   $$b$$,
   $${"a": "Consistency beats grand gestures.", "c": "Agreeableness isn't reliability.", "d": "Seniority doesn't build trust on its own."}$$,
   $$easy$$),
  (4, $$Why is a surprise a withdrawal even when the news itself is neutral?$$,
   $$[{"id": "a", "text": "Surprises are always good news"}, {"id": "b", "text": "Being caught off guard erodes a stakeholder's sense that you'll keep them informed — the 'no surprises' principle"}, {"id": "c", "text": "Surprises violate the contract"}, {"id": "d", "text": "Neutral news never matters"}]$$,
   $$b$$,
   $${"a": "The point is the lack of warning, not the news.", "c": "It's a trust issue, not a contractual one.", "d": "Even neutral news lands badly when it's a surprise."}$$,
   $$medium$$),
  (5, $$Giving credit where it's due is a deposit because:$$,
   $$[{"id": "a", "text": "It makes you look generous to the sponsor"}, {"id": "b", "text": "Passing credit to the people who did the work builds their trust in you and signals you won't claim what isn't yours"}, {"id": "c", "text": "It is required by policy"}, {"id": "d", "text": "It lets you avoid doing the work yourself"}]$$,
   $$b$$,
   $${"a": "The motive isn't self-image.", "c": "It's about trust, not policy.", "d": "Crediting others isn't about offloading work."}$$,
   $$medium$$),
  (6, $$The chapter stresses that a relationship is with:$$,
   $$[{"id": "a", "text": "A role on the org chart"}, {"id": "b", "text": "A specific person — remembering their context, pressures, and preferences, not just their title"}, {"id": "c", "text": "The whole department at once"}, {"id": "d", "text": "The project, abstractly"}]$$,
   $$b$$,
   $${"a": "Roles change; you build trust with the person.", "c": "Relationships are individual.", "d": "Abstractions don't hold trust; people do."}$$,
   $$medium$$),
  (7, $$Tailoring how you communicate to each stakeholder means:$$,
   $$[{"id": "a", "text": "Telling each person whatever keeps them happy"}, {"id": "b", "text": "Matching real preferences — the surprise-averse get early warning, the detail-oriented get detail, the bottom-line get the headline"}, {"id": "c", "text": "Sending everyone the identical update"}, {"id": "d", "text": "Only talking to senior stakeholders"}]$$,
   $$b$$,
   $${"a": "Tailoring style isn't telling people what they want to hear.", "c": "Identical updates ignore real differences.", "d": "All stakeholders need stewarding."}$$,
   $$medium$$),
  (8, $$When you DO make a withdrawal (miss a commitment), the chapter says you should:$$,
   $$[{"id": "a", "text": "Hide it and hope no one notices"}, {"id": "b", "text": "Acknowledge it directly and early, own it, and propose the fix — a repair handled well can actually deepen trust"}, {"id": "c", "text": "Blame the stakeholder for unclear expectations"}, {"id": "d", "text": "Wait until they raise it"}]$$,
   $$b$$,
   $${"a": "Hiding it compounds the withdrawal when discovered.", "c": "Blame-shifting is another withdrawal.", "d": "Proactive repair beats waiting to be caught."}$$,
   $$medium$$),
  (9, $$Across PM or leadership transitions, the coordinator often provides:$$,
   $$[{"id": "a", "text": "Nothing — relationships reset"}, {"id": "b", "text": "Continuity — the steady relationship and institutional memory that carries the stakeholder trust across the change"}, {"id": "c", "text": "A reason to restart the project"}, {"id": "d", "text": "A formal handover document only"}]$$,
   $$b$$,
   $${"a": "The coordinator is frequently the through-line.", "c": "Continuity, not a restart.", "d": "It's living continuity, not just a document."}$$,
   $$medium$$),
  (10, $$The integrity line in relationship stewardship is the difference between:$$,
   $$[{"id": "a", "text": "Being friendly vs being formal"}, {"id": "b", "text": "Building genuine relationships to serve the work and the people, vs cultivating people purely instrumentally to extract advantage"}, {"id": "c", "text": "Talking a lot vs talking little"}, {"id": "d", "text": "Knowing names vs knowing titles"}]$$,
   $$b$$,
   $${"a": "Tone isn't the integrity question.", "c": "Volume isn't the issue.", "d": "It's about motive, not memory."}$$,
   $$hard$$),
  (11, $$Why does the chapter call relationship stewardship 'the long game'?$$,
   $$[{"id": "a", "text": "Relationships only matter at project end"}, {"id": "b", "text": "Your reputation for reliability compounds across projects and years — people remember how you treated them"}, {"id": "c", "text": "It takes years to send a single update"}, {"id": "d", "text": "Trust never changes once set"}]$$,
   $$b$$,
   $${"a": "It matters throughout, and beyond this project.", "c": "Hyperbole, not the point.", "d": "Trust is continually earned or eroded."}$$,
   $$medium$$),
  (12, $$People start routing requests and information through a coordinator who:$$,
   $$[{"id": "a", "text": "Has the most authority"}, {"id": "b", "text": "Has proven reliable — they trust things won't get dropped, so the coordinator becomes a dependable node in the network"}, {"id": "c", "text": "Responds the fastest regardless of follow-through"}, {"id": "d", "text": "Is friends with the sponsor"}]$$,
   $$b$$,
   $${"a": "Routing follows trust, not title.", "c": "Speed without follow-through erodes trust.", "d": "Proximity to power isn't reliability."}$$,
   $$medium$$),
  (13, $$One failure mode of relationship stewardship is people-pleasing, which looks like:$$,
   $$[{"id": "a", "text": "Telling hard truths plainly"}, {"id": "b", "text": "Avoiding uncomfortable truths to keep stakeholders happy — which is a false deposit that fails them when it matters"}, {"id": "c", "text": "Following up on small commitments"}, {"id": "d", "text": "Tailoring communication style"}]$$,
   $$b$$,
   $${"a": "That's healthy, not the failure.", "c": "That's a genuine deposit.", "d": "That's legitimate stewardship."}$$,
   $$medium$$),
  (14, $$Delivering an uncomfortable truth, done with care, is best understood as:$$,
   $$[{"id": "a", "text": "Always a withdrawal"}, {"id": "b", "text": "A deposit — it shows the stakeholder you'll tell them what they need to hear, which is the basis of real trust"}, {"id": "c", "text": "A breach of the relationship"}, {"id": "d", "text": "Something to delegate to the PM"}]$$,
   $$b$$,
   $${"a": "Honesty handled well builds, not depletes, trust.", "c": "It strengthens rather than breaches it.", "d": "The steward shouldn't outsource candour."}$$,
   $$hard$$),
  (15, $$The other failure mode — treating relationships purely transactionally — fails because:$$,
   $$[{"id": "a", "text": "It builds too much trust"}, {"id": "b", "text": "People sense when they're being used, and instrumental cultivation eventually erodes the very trust it tried to manufacture"}, {"id": "c", "text": "It is against company policy"}, {"id": "d", "text": "It takes too long"}]$$,
   $$b$$,
   $${"a": "It produces too little real trust, not too much.", "c": "It's a trust failure, not a policy one.", "d": "Speed isn't the problem."}$$,
   $$medium$$),
  (16, $$Keeping a confidence a stakeholder shares with you is:$$,
   $$[{"id": "a", "text": "A withdrawal"}, {"id": "b", "text": "A deposit — discretion signals you can be trusted with sensitive information"}, {"id": "c", "text": "Irrelevant to trust"}, {"id": "d", "text": "Only relevant for senior stakeholders"}]$$,
   $$b$$,
   $${"a": "Discretion builds trust, not erodes it.", "c": "It's central to trust.", "d": "It applies to everyone."}$$,
   $$easy$$),
  (17, $$Closing the loop — telling someone the outcome of a thing they raised — matters because:$$,
   $$[{"id": "a", "text": "It pads your status report"}, {"id": "b", "text": "Unclosed loops quietly accumulate as small withdrawals; following through to the end is a steady stream of deposits"}, {"id": "c", "text": "It is only needed for formal change requests"}, {"id": "d", "text": "It impresses the sponsor"}]$$,
   $$b$$,
   $${"a": "It's about trust, not padding.", "c": "It applies to everyday follow-ups too.", "d": "The point is reliability, not impressing anyone."}$$,
   $$medium$$),
  (18, $$Knowing what a stakeholder actually cares about (their real goals and pressures) lets you:$$,
   $$[{"id": "a", "text": "Manipulate them"}, {"id": "b", "text": "Steward the relationship better — anticipate what they need and frame information in terms that matter to them"}, {"id": "c", "text": "Ignore the rest of the stakeholders"}, {"id": "d", "text": "Skip the status report"}]$$,
   $$b$$,
   $${"a": "Understanding to help is stewardship; to exploit is the integrity breach.", "c": "You steward all relevant stakeholders.", "d": "Understanding goals doesn't replace reporting."}$$,
   $$medium$$),
  (19, $$Why does playing favourites undermine a coordinator's stewardship?$$,
   $$[{"id": "a", "text": "It builds trust with everyone"}, {"id": "b", "text": "Visible favouritism withdraws trust from everyone NOT favoured, and signals your reliability is conditional rather than even-handed"}, {"id": "c", "text": "It is efficient"}, {"id": "d", "text": "Favourites always reciprocate"}]$$,
   $$b$$,
   $${"a": "It erodes trust broadly.", "c": "Efficiency isn't the issue.", "d": "Even if they did, the broader trust cost remains."}$$,
   $$medium$$),
  (20, $$Ultimately, the steward role means the coordinator holds relationships:$$,
   $$[{"id": "a", "text": "For personal advancement"}, {"id": "b", "text": "On behalf of the project — caring for them as a shared asset, not as private leverage"}, {"id": "c", "text": "Only until the next PM arrives"}, {"id": "d", "text": "As a formal contractual duty"}]$$,
   $$b$$,
   $${"a": "Personal leverage is the integrity-line failure.", "c": "Stewardship persists across transitions.", "d": "It's a trust duty, not a contractual one."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'stakeholder-relationships'
on conflict do nothing;
