-- Seed 20 quiz items for Lesson 22 (vendors). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'vendors');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'vendor_partnership', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$The core posture the chapter prescribes toward a vendor is:$$,
   $$[{"id": "a", "text": "Treat them as staff who should absorb extra scope"}, {"id": "b", "text": "Professional partnership — firm on what the contract requires, but neither treating them as employees nor as adversaries"}, {"id": "c", "text": "Treat them as adversaries trying to gouge you"}, {"id": "d", "text": "Defer to whatever they propose to keep them happy"}]$$,
   $$b$$,
   $${"a": "They're a partner with their own margins, not your staff.", "c": "The adversary stance is one of the two failure modes.", "d": "Capitulation is the other failure mode."}$$,
   $$medium$$),
  (2, $$A vendor is best understood as:$$,
   $$[{"id": "a", "text": "Your employee"}, {"id": "b", "text": "A real business with its own margins and pressures — not your employee and not your enemy"}, {"id": "c", "text": "An adversary"}, {"id": "d", "text": "A charity that should work at cost"}]$$,
   $$b$$,
   $${"a": "They aren't staff under your direction.", "c": "Treating them as an enemy is a failure mode.", "d": "They're entitled to their margins."}$$,
   $$easy$$),
  (3, $$When a change request's scope looks already covered by the Statement of Work, you should frame the dispute as:$$,
   $$[{"id": "a", "text": "A character question about the vendor's honesty"}, {"id": "b", "text": "A contract/SOW question — point precisely to the relevant section and what it covers"}, {"id": "c", "text": "A reason to terminate the contract"}, {"id": "d", "text": "Something to quietly approve to avoid friction"}]$$,
   $$b$$,
   $${"a": "Make it about the document, not the vendor's character.", "c": "That's disproportionate to a scope dispute.", "d": "Approving in-scope work to avoid friction is capitulation."}$$,
   $$medium$$),
  (4, $$Holding a missed commitment to account 'without being punitive' means:$$,
   $$[{"id": "a", "text": "Softening it so no one feels bad"}, {"id": "b", "text": "Naming the specific miss, asking the vendor's view, and agreeing a corrective action / heads-up protocol — without threatening breach"}, {"id": "c", "text": "Threatening to invoke breach immediately"}, {"id": "d", "text": "Escalating straight to their executives"}]$$,
   $$b$$,
   $${"a": "Softening lets a critical miss slide.", "c": "Threatening breach over a slip is punitive and disproportionate.", "d": "Escalation comes after private resolution fails."}$$,
   $$medium$$),
  (5, $$When a vendor has missed twice, the chapter says to:$$,
   $$[{"id": "a", "text": "Ignore the pattern and treat each as isolated"}, {"id": "b", "text": "Name the second miss specifically and ask for a corrective action / heads-up protocol so it isn't a third"}, {"id": "c", "text": "Demand a penalty payment"}, {"id": "d", "text": "Stop working with them"}]$$,
   $$b$$,
   $${"a": "A pattern is exactly what to name.", "c": "Penalty demands are punitive escalation, not the first step.", "d": "That's disproportionate to two slips."}$$,
   $$medium$$),
  (6, $$Respecting the vendor's internal structure means:$$,
   $$[{"id": "a", "text": "Going straight to their executives when something slips"}, {"id": "b", "text": "Working through your day-to-day counterpart rather than around them, and reserving formal escalation for when private resolution fails"}, {"id": "c", "text": "Never speaking to anyone but the account manager"}, {"id": "d", "text": "CCing their whole leadership on every issue"}]$$,
   $$b$$,
   $${"a": "Going around your counterpart undermines the partnership.", "c": "You work primarily through your counterpart, but escalation exists if needed.", "d": "Broadcasting issues is punitive and disproportionate."}$$,
   $$medium$$),
  (7, $$The chapter's stance on a written record of specifics is:$$,
   $$[{"id": "a", "text": "Avoid writing things down to keep things friendly"}, {"id": "b", "text": "Keep a clear written record of the specifics — it protects both sides and keeps the facts straight"}, {"id": "c", "text": "Only the vendor should keep records"}, {"id": "d", "text": "Records are only for the legal team"}]$$,
   $$b$$,
   $${"a": "A friendly tone and a clear record aren't in tension.", "c": "You keep your own record.", "d": "The PC keeps a working record, not just lawyers."}$$,
   $$medium$$),
  (8, $$'Stay proportionate' in a vendor dispute means:$$,
   $$[{"id": "a", "text": "Escalate formally at the first sign of trouble"}, {"id": "b", "text": "Try private conversation before any formal step, and match the response to the size of the problem"}, {"id": "c", "text": "Never escalate under any circumstances"}, {"id": "d", "text": "Always involve the Steering Committee"}]$$,
   $$b$$,
   $${"a": "Formal-first is disproportionate.", "c": "Escalation is reserved, not forbidden.", "d": "You don't reflexively pull in the SteerCo."}$$,
   $$medium$$),
  (9, $$Crediting good work the vendor has done is important because:$$,
   $$[{"id": "a", "text": "It obligates them to discount future work"}, {"id": "b", "text": "It keeps the partnership honest and balanced — accountability for misses sits alongside recognition of what they did well"}, {"id": "c", "text": "It is contractually required"}, {"id": "d", "text": "It replaces the need to address misses"}]$$,
   $$b$$,
   $${"a": "Credit isn't a lever for discounts.", "c": "It's good practice, not a clause.", "d": "Credit accompanies, not replaces, accountability."}$$,
   $$medium$$),
  (10, $$The 'adversary' failure mode looks like:$$,
   $$[{"id": "a", "text": "Treating the vendor as an enemy to be squeezed — punitive, suspicious, threatening breach over normal slips"}, {"id": "b", "text": "Approving every change request"}, {"id": "c", "text": "Working through your counterpart"}, {"id": "d", "text": "Keeping a written record"}]$$,
   $$a$$,
   $${"b": "That's the pushover failure mode.", "c": "That's correct practice.", "d": "That's correct practice."}$$,
   $$medium$$),
  (11, $$The 'pushover' (capitulation) failure mode looks like:$$,
   $$[{"id": "a", "text": "Naming a miss firmly"}, {"id": "b", "text": "Approving an in-scope CR and letting a critical-path miss slide to avoid friction — capitulation dressed up as relationship-management"}, {"id": "c", "text": "Pointing to the SOW section"}, {"id": "d", "text": "Asking for a corrective-action protocol"}]$$,
   $$b$$,
   $${"a": "Firmness is correct, not a failure.", "c": "That's correct practice.", "d": "That's correct practice."}$$,
   $$medium$$),
  (12, $$If the account manager CCs your sponsor's office on a disputed CR, the proportionate response is to:$$,
   $$[{"id": "a", "text": "Approve it immediately so the sponsor sees no conflict"}, {"id": "b", "text": "Work the substance with your counterpart on the SOW basis first, keeping your own record, rather than litigating it up the chain pre-emptively"}, {"id": "c", "text": "CC the vendor's executives in retaliation"}, {"id": "d", "text": "Ignore the CR entirely"}]$$,
   $$b$$,
   $${"a": "Approving an in-scope CR to look smooth is capitulation.", "c": "Retaliatory escalation is the adversary mode.", "d": "The CR needs a reasoned response, not silence."}$$,
   $$hard$$),
  (13, $$Distinguishing 'additional scope' from 'already in scope' requires:$$,
   $$[{"id": "a", "text": "Trusting the vendor's framing"}, {"id": "b", "text": "Reading the CR against the actual SOW and judging whether the work is already covered"}, {"id": "c", "text": "Asking the sponsor to decide"}, {"id": "d", "text": "Approving if the amount is small"}]$$,
   $$b$$,
   $${"a": "You verify against the document, not the framing.", "c": "It's first a scope analysis you can do.", "d": "Size doesn't determine whether it's in scope."}$$,
   $$medium$$),
  (14, $$Why does the chapter warn against treating a critical-path miss as 'no big deal' to keep the peace?$$,
   $$[{"id": "a", "text": "It builds trust"}, {"id": "b", "text": "Letting a critical-path slip slide unaddressed quietly costs the project schedule and signals misses carry no consequence"}, {"id": "c", "text": "It is against the contract"}, {"id": "d", "text": "It always triggers breach"}]$$,
   $$b$$,
   $${"a": "Avoidance erodes the partnership's reliability.", "c": "It's a delivery/accountability issue, not automatically contractual.", "d": "It doesn't automatically trigger breach."}$$,
   $$medium$$),
  (15, $$A 'heads-up protocol' agreed after a missed commitment is meant to:$$,
   $$[{"id": "a", "text": "Punish the vendor for the past miss"}, {"id": "b", "text": "Ensure you get early warning of future slips so they don't become surprises on the critical path"}, {"id": "c", "text": "Replace the contract"}, {"id": "d", "text": "Give the vendor a reason to slip again"}]$$,
   $$b$$,
   $${"a": "It's forward-looking, not punitive.", "c": "It supplements, not replaces, the contract.", "d": "It reduces, not enables, surprises."}$$,
   $$medium$$),
  (16, $$When your counterpart has 'generally been straight with you,' the chapter says to:$$,
   $$[{"id": "a", "text": "Assume the dispute proves they were lying all along"}, {"id": "b", "text": "Hold the specific issue to account while not rewriting the whole relationship around one CR or one slip"}, {"id": "c", "text": "Drop the issue because of past goodwill"}, {"id": "d", "text": "Escalate over their head anyway"}]$$,
   $$b$$,
   $${"a": "One dispute doesn't erase a track record.", "c": "Goodwill doesn't mean ignoring the issue.", "d": "Going over their head breaches the partnership."}$$,
   $$medium$$),
  (17, $$The relationship with a vendor is best treated as:$$,
   $$[{"id": "a", "text": "A one-off transaction with no future"}, {"id": "b", "text": "Potentially long-term — reputation runs both ways, so how you handle disputes shapes future engagements"}, {"id": "c", "text": "Purely adversarial"}, {"id": "d", "text": "Irrelevant once the SOW is signed"}]$$,
   $$b$$,
   $${"a": "You may work with them again.", "c": "Adversarial framing is a failure mode.", "d": "The relationship is managed throughout delivery."}$$,
   $$medium$$),
  (18, $$Being 'firm on what the contract requires' is compatible with partnership because:$$,
   $$[{"id": "a", "text": "Firmness and partnership are opposites"}, {"id": "b", "text": "Clear expectations grounded in the contract are how good partners work — firmness is about the work, not hostility toward the vendor"}, {"id": "c", "text": "Partners never disagree"}, {"id": "d", "text": "The contract doesn't matter between partners"}]$$,
   $$b$$,
   $${"a": "They reinforce each other.", "c": "Good partners disagree and resolve it on the facts.", "d": "The contract is the shared basis, not an irrelevance."}$$,
   $$medium$$),
  (19, $$The right sequence when a vendor disputes scope and has also missed a deadline is to:$$,
   $$[{"id": "a", "text": "Threaten breach and approve the CR simultaneously"}, {"id": "b", "text": "Address both directly and proportionately — anchor the CR to the SOW, name the miss and seek corrective action, in a private conversation first"}, {"id": "c", "text": "Pick only the easier one to raise"}, {"id": "d", "text": "Escalate both to the Steering Committee immediately"}]$$,
   $$b$$,
   $${"a": "That mixes both failure modes at once.", "c": "Both issues warrant a response.", "d": "Private resolution precedes SteerCo escalation."}$$,
   $$hard$$),
  (20, $$The underlying principle of vendor partnership is:$$,
   $$[{"id": "a", "text": "Win every interaction"}, {"id": "b", "text": "Hold the contract and the relationship together — accountable and precise on the work, respectful and proportionate toward the partner"}, {"id": "c", "text": "Keep the vendor happy at any cost"}, {"id": "d", "text": "Minimise all contact with the vendor"}]$$,
   $$b$$,
   $${"a": "Winning-at-all-costs is the adversary mode.", "c": "Happy-at-any-cost is the pushover mode.", "d": "Partnership requires engagement, not avoidance."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'vendors'
on conflict do nothing;
