-- Seed 20 quiz items for Lesson 18 (chasing). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'chasing');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'chase_judgment', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$The chapter's 'seventeen nudges' story illustrates:$$,
   $$[{"id": "a", "text": "Admirable persistence"}, {"id": "b", "text": "Ceremonial chasing — nudging past the point of usefulness as an accumulated habit rather than purposeful work, on a deliverable that no longer mattered"}, {"id": "c", "text": "A vendor breach"}, {"id": "d", "text": "A critical-path failure"}]$$,
   $$b$$,
   $${"a": "It's the opposite — wasted, ceremonial effort.", "c": "No breach; the item was just dead.", "d": "It was a soft dependency, off the critical path."}$$,
   $$medium$$),
  (2, $$Chasing is useful when:$$,
   $$[{"id": "a", "text": "The commitment is dead and prompting won't revive it"}, {"id": "b", "text": "The commitment is still live and reasonable prompting can produce action"}, {"id": "c", "text": "You need to close an action on the tracker"}, {"id": "d", "text": "You are annoyed"}]$$,
   $$b$$,
   $${"a": "That's exactly when chasing is wasted.", "c": "Closing the tracker isn't the purpose of a chase.", "d": "Annoyance is a reason to wait, not chase."}$$,
   $$medium$$),
  (3, $$The hard part of chasing is:$$,
   $$[{"id": "a", "text": "Writing a polite email"}, {"id": "b", "text": "Distinguishing a live commitment (worth chasing) from a dead one (where prompting won't help)"}, {"id": "c", "text": "Finding the person's email address"}, {"id": "d", "text": "Choosing a font"}]$$,
   $$b$$,
   $${"a": "Wording is secondary to the judgement.", "c": "Trivial, not the hard part.", "d": "Not relevant."}$$,
   $$medium$$),
  (4, $$Which is a signal that a chase is STILL useful?$$,
   $$[{"id": "a", "text": "The person has stopped responding across several nudges"}, {"id": "b", "text": "The person is responsive — even a 'sorry, still on it' reply shows the commitment is alive in their mind"}, {"id": "c", "text": "The deliverable is no longer needed"}, {"id": "d", "text": "Repeated nudges produce no movement"}]$$,
   $$b$$,
   $${"a": "That's a stop-signal.", "c": "That's a stop-signal.", "d": "That's a stop-signal."}$$,
   $$medium$$),
  (5, $$Which is a signal you should STOP chasing?$$,
   $$[{"id": "a", "text": "The person replies to every nudge"}, {"id": "b", "text": "The person has gone unresponsive across multiple nudges over time"}, {"id": "c", "text": "A temporary blocker has just lifted"}, {"id": "d", "text": "Gentle prompting is producing partial progress"}]$$,
   $$b$$,
   $${"a": "Responsiveness means the commitment is alive.", "c": "A resolving cause means the chase is still useful.", "d": "Movement means keep going."}$$,
   $$medium$$),
  (6, $$When a chase has run its course, the three available paths are:$$,
   $$[{"id": "a", "text": "Nudge harder, wait, or give up silently"}, {"id": "b", "text": "Escalate (still needed, owner not producing), reclassify (convert the need to a risk with a mitigation), or let it go (no longer needed, close it)"}, {"id": "c", "text": "Blame, delay, or hide it"}, {"id": "d", "text": "Report it green, amber, or red"}]$$,
   $$b$$,
   $${"a": "'Nudge harder' is the trap; the three real paths are escalate/reclassify/let-go.", "c": "None of those are the chapter's paths.", "d": "RAG ratings aren't chase paths."}$$,
   $$medium$$),
  (7, $$You should escalate (rather than let go) when:$$,
   $$[{"id": "a", "text": "The deliverable is no longer needed"}, {"id": "b", "text": "The deliverable is STILL needed and the owner is not producing it"}, {"id": "c", "text": "You're tired of chasing"}, {"id": "d", "text": "The item is off the critical path and redundant"}]$$,
   $$b$$,
   $${"a": "If it's not needed, let it go — don't escalate.", "c": "Fatigue isn't a reason to escalate.", "d": "A redundant item warrants let-go, not escalation."}$$,
   $$medium$$),
  (8, $$To 'reclassify' a dead chase means to:$$,
   $$[{"id": "a", "text": "Keep it open and nudge weekly"}, {"id": "b", "text": "Close the action as dropped and convert the underlying need into a risk/issue with a mitigation and owner"}, {"id": "c", "text": "Delete it with no record"}, {"id": "d", "text": "Escalate it to the sponsor"}]$$,
   $$b$$,
   $${"a": "That's ceremonial chasing, not reclassifying.", "c": "You preserve the record, not erase it.", "d": "That's escalation, a different path."}$$,
   $$medium$$),
  (9, $$Closing an undelivered-but-no-longer-needed action is:$$,
   $$[{"id": "a", "text": "Admitting failure"}, {"id": "b", "text": "Accurate record-keeping — the real failure is a tracker full of nominally-open items nobody expects to close"}, {"id": "c", "text": "Against governance"}, {"id": "d", "text": "Only the PM's call"}]$$,
   $$b$$,
   $${"a": "That feeling is exactly the trap the chapter names.", "c": "Honest closure is good governance.", "d": "The coordinator can close it with a note."}$$,
   $$medium$$),
  (10, $$A well-written chase is:$$,
   $$[{"id": "a", "text": "'Following up.'"}, {"id": "b", "text": "Specific — 'Just checking on the vendor summary for next week's SC pack — do you have a view on timing?'"}, {"id": "c", "text": "'Please respond ASAP.'"}, {"id": "d", "text": "A blank reminder"}]$$,
   $$b$$,
   $${"a": "Vague — 'following up' says nothing specific.", "c": "Demanding and non-specific.", "d": "A blank nudge gives nothing to act on."}$$,
   $$easy$$),
  (11, $$The chapter says a chase should be:$$,
   $$[{"id": "a", "text": "Apologetic — 'so sorry to bother you, I know you're swamped'"}, {"id": "b", "text": "Polite but NOT apologetic — 'just checking' is fine; you are doing your job"}, {"id": "c", "text": "Stern and demanding"}, {"id": "d", "text": "Anonymous"}]$$,
   $$b$$,
   $${"a": "Grovelling is the anti-pattern.", "c": "Sternness hurts the relationship.", "d": "Chases are personal and direct."}$$,
   $$medium$$),
  (12, $$'Make it easy to respond' means:$$,
   $$[{"id": "a", "text": "Ask a broad open question"}, {"id": "b", "text": "Offer options — 'Should I plan on Friday, or would Monday work better?' — yes/no and either/or get faster answers"}, {"id": "c", "text": "Demand a same-day reply"}, {"id": "d", "text": "Cc their whole team"}]$$,
   $$b$$,
   $${"a": "Open questions get slower responses.", "c": "Pressure isn't the move.", "d": "Cc'ing the team is pressure, not ease."}$$,
   $$medium$$),
  (13, $$'Offer help' in a chase is useful because:$$,
   $$[{"id": "a", "text": "It guilts the person into replying"}, {"id": "b", "text": "Sometimes the block is something the person would be embarrassed to name; offering help makes it easy to ask"}, {"id": "c", "text": "It's required by policy"}, {"id": "d", "text": "It shifts the work to you permanently"}]$$,
   $$b$$,
   $${"a": "It's genuine help, not guilt.", "c": "No policy mandates it.", "d": "It's an offer, not a permanent transfer."}$$,
   $$medium$$),
  (14, $$'Vary the channel occasionally' means:$$,
   $$[{"id": "a", "text": "Send the same email ten times"}, {"id": "b", "text": "If three emails go unanswered, try Slack or a short in-person check-in — varying channel can break inertia without feeling like pressure"}, {"id": "c", "text": "Escalate to the sponsor"}, {"id": "d", "text": "Switch to a more formal tone"}]$$,
   $$b$$,
   $${"a": "Repeating the same channel is ceremonial.", "c": "Channel-varying isn't escalation.", "d": "It's about channel, not register."}$$,
   $$medium$$),
  (15, $$The tone of a chase throughout should be:$$,
   $$[{"id": "a", "text": "Increasingly irritated"}, {"id": "b", "text": "Patient professionalism — you're tracking, not annoyed; if you feel annoyed, wait before sending, because the annoyance will leak through"}, {"id": "c", "text": "Cold and clipped"}, {"id": "d", "text": "Whatever gets the fastest reply"}]$$,
   $$b$$,
   $${"a": "Irritation hurts the relationship without helping.", "c": "Coldness reads as pressure.", "d": "Speed isn't worth a damaged relationship."}$$,
   $$medium$$),
  (16, $$'Chasing is producing no movement' (after repeated nudges) is:$$,
   $$[{"id": "a", "text": "A reason to nudge harder"}, {"id": "b", "text": "A stop-signal — you're spending energy on a dead loop"}, {"id": "c", "text": "Normal and fine"}, {"id": "d", "text": "A reason to apologise"}]$$,
   $$b$$,
   $${"a": "Harder nudging on a dead loop is the trap.", "c": "It's a signal to change the move.", "d": "Apologising doesn't address a dead loop."}$$,
   $$medium$$),
  (17, $$The owner was on leave and is now back, or a cross-team blocker has lifted. This is:$$,
   $$[{"id": "a", "text": "A stop-signal — let it go"}, {"id": "b", "text": "A resolving cause — a signal the chase is still useful"}, {"id": "c", "text": "Irrelevant to the chase"}, {"id": "d", "text": "Grounds for escalation"}]$$,
   $$b$$,
   $${"a": "A lifting constraint is a keep-going signal, not a stop.", "c": "It's directly relevant.", "d": "Escalation isn't warranted just because a blocker cleared."}$$,
   $$medium$$),
  (18, $$Before sending a THIRD nudge on the same item, the chapter says to:$$,
   $$[{"id": "a", "text": "Just send it"}, {"id": "b", "text": "Stop and ask whether a different move (escalate, reclassify, or let go) is needed instead"}, {"id": "c", "text": "Cc the sponsor"}, {"id": "d", "text": "Mark the action complete"}]$$,
   $$b$$,
   $${"a": "Reflexively sending is the ceremonial trap.", "c": "Cc'ing the sponsor is disproportionate.", "d": "Marking it complete when it isn't corrupts the record."}$$,
   $$medium$$),
  (19, $$A tracker with many nominally-open actions that nobody expects to close is:$$,
   $$[{"id": "a", "text": "A sign of thoroughness"}, {"id": "b", "text": "Clutter that obscures what is actually live — the real failure the chapter warns about"}, {"id": "c", "text": "Required for audit"}, {"id": "d", "text": "Better than closing items"}]$$,
   $$b$$,
   $${"a": "It's clutter, not thoroughness.", "c": "Audit wants an honest, current tracker.", "d": "Honest closure beats ceremonial openness."}$$,
   $$medium$$),
  (20, $$Overall, the skill the chapter teaches is:$$,
   $$[{"id": "a", "text": "Always chase until delivered"}, {"id": "b", "text": "Reading the live-vs-dead signals and matching the move — chase, escalate, reclassify, or let go — to them"}, {"id": "c", "text": "Never chase anyone"}, {"id": "d", "text": "Escalate every overdue item"}]$$,
   $$b$$,
   $${"a": "Chasing to the bitter end is the seventeen-nudge failure.", "c": "Chasing is a real and useful part of the job when warranted.", "d": "Escalating everything is disproportionate."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'chasing'
on conflict do nothing;
