-- Seed 20 quiz items for Lesson 24 (using-ai). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'using-ai');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'ai_tool_judgment', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$The chapter's core stance on AI tools for a coordinator is:$$,
   $$[{"id": "a", "text": "Avoid them — they're too risky"}, {"id": "b", "text": "Use them as powerful assistants for drafting and structuring, while keeping ownership and judgement of the output firmly with you"}, {"id": "c", "text": "Trust their output as authoritative"}, {"id": "d", "text": "Use them only for trivial tasks"}]$$,
   $$b$$,
   $${"a": "Refusing a genuinely useful tool is a failure mode.", "c": "Blind trust is the other failure mode.", "d": "They help with substantive drafting too, with judgement applied."}$$,
   $$medium$$),
  (2, $$AI tools are strongest at:$$,
   $$[{"id": "a", "text": "Final accountability for decisions"}, {"id": "b", "text": "Drafting, summarising, restructuring, and brainstorming — producing a first pass you then refine"}, {"id": "c", "text": "Knowing your project's confidential context"}, {"id": "d", "text": "Guaranteeing factual accuracy"}]$$,
   $$b$$,
   $${"a": "Accountability can't be delegated to a tool.", "c": "It doesn't know context you haven't given it.", "d": "It can produce confident errors."}$$,
   $$medium$$),
  (3, $$Because AI can produce confident but wrong output, the coordinator must:$$,
   $$[{"id": "a", "text": "Send it as-is to save time"}, {"id": "b", "text": "Verify facts, numbers, names, and claims before relying on or sending anything"}, {"id": "c", "text": "Assume long answers are more accurate"}, {"id": "d", "text": "Trust it if it sounds fluent"}]$$,
   $$b$$,
   $${"a": "Unchecked output is the over-trust failure.", "c": "Length doesn't indicate accuracy.", "d": "Fluency is not correctness."}$$,
   $$easy$$),
  (4, $$'The AI said so' as a justification for an error is:$$,
   $$[{"id": "a", "text": "A valid excuse"}, {"id": "b", "text": "Not an excuse — accountability for anything you send or act on stays with you, not the tool"}, {"id": "c", "text": "Acceptable for low-stakes work"}, {"id": "d", "text": "The PM's problem"}]$$,
   $$b$$,
   $${"a": "Responsibility doesn't transfer to a tool.", "c": "Accountability holds regardless of stakes.", "d": "It's the coordinator's output and responsibility."}$$,
   $$medium$$),
  (5, $$The right mental model for an AI draft is:$$,
   $$[{"id": "a", "text": "A finished deliverable"}, {"id": "b", "text": "A first draft to review, correct, and apply judgement to — not the final word"}, {"id": "c", "text": "A source of truth"}, {"id": "d", "text": "A reason to skip understanding the work"}]$$,
   $$b$$,
   $${"a": "It's a starting point, not a finished product.", "c": "It isn't authoritative.", "d": "You still need to understand the material."}$$,
   $$medium$$),
  (6, $$On confidentiality, the chapter says:$$,
   $$[{"id": "a", "text": "Paste anything in — it's private"}, {"id": "b", "text": "Don't put sensitive or confidential project data into tools that aren't approved for it"}, {"id": "c", "text": "Confidentiality doesn't apply to AI"}, {"id": "d", "text": "Only worry about it for financial data"}]$$,
   $$b$$,
   $${"a": "Inputs may not be private; check approval first.", "c": "Confidentiality very much applies.", "d": "It applies to all sensitive data, not just financial."}$$,
   $$medium$$),
  (7, $$AI tools are weakest at:$$,
   $$[{"id": "a", "text": "Rephrasing text"}, {"id": "b", "text": "Judgement, current facts they weren't given, and anything requiring genuine accountability or unshared context"}, {"id": "c", "text": "Producing a structured outline"}, {"id": "d", "text": "Summarising a long document you provide"}]$$,
   $$b$$,
   $${"a": "Rephrasing is a strength.", "c": "Outlining is a strength.", "d": "Summarising provided text is a strength."}$$,
   $$medium$$),
  (8, $$The 'human-in-the-loop' discipline means:$$,
   $$[{"id": "a", "text": "A human reviews and owns the output before it goes anywhere"}, {"id": "b", "text": "A human is cc'd on the AI's emails"}, {"id": "c", "text": "The AI checks the human's work"}, {"id": "d", "text": "Two AIs review each other"}]$$,
   $$a$$,
   $${"b": "It's about review and ownership, not cc lists.", "c": "The human reviews the AI, not the reverse.", "d": "The loop requires a human, not another model."}$$,
   $$medium$$),
  (9, $$One failure mode is OVER-trust, which looks like:$$,
   $$[{"id": "a", "text": "Verifying figures before sending"}, {"id": "b", "text": "Sending AI output unchecked so hallucinated facts slip through, or pasting confidential data into an unapproved tool"}, {"id": "c", "text": "Using AI to draft an outline"}, {"id": "d", "text": "Refusing to use AI at all"}]$$,
   $$b$$,
   $${"a": "That's correct practice.", "c": "That's appropriate use.", "d": "That's the opposite failure mode."}$$,
   $$medium$$),
  (10, $$The opposite failure mode is UNDER-use, which looks like:$$,
   $$[{"id": "a", "text": "Checking AI output for errors"}, {"id": "b", "text": "Refusing a genuinely helpful tool out of fear or habit, doing slower work that the tool could have accelerated with judgement applied"}, {"id": "c", "text": "Keeping confidential data out of unapproved tools"}, {"id": "d", "text": "Owning the final output"}]$$,
   $$b$$,
   $${"a": "That's correct practice.", "c": "That's correct practice.", "d": "That's correct practice."}$$,
   $$medium$$),
  (11, $$Using AI to skip actually understanding the work is a trap because:$$,
   $$[{"id": "a", "text": "It is too slow"}, {"id": "b", "text": "You still need to understand the material to catch the tool's errors and stand behind the output — outsourcing the thinking leaves you unable to do either"}, {"id": "c", "text": "It is against policy"}, {"id": "d", "text": "AI understands it for you"}]$$,
   $$b$$,
   $${"a": "Speed isn't the issue.", "c": "It's a competence/accountability issue, not just policy.", "d": "You can't rely on the tool's understanding in place of your own."}$$,
   $$hard$$),
  (12, $$Matching the tool to the task means:$$,
   $$[{"id": "a", "text": "Using AI identically for every task"}, {"id": "b", "text": "Weighing the stakes — light verification for a low-stakes draft, rigorous checking for anything high-stakes or externally sent"}, {"id": "c", "text": "Only using AI for high-stakes work"}, {"id": "d", "text": "Avoiding AI for anything that matters"}]$$,
   $$b$$,
   $${"a": "Stakes should scale the scrutiny.", "c": "AI helps with low-stakes work too.", "d": "It can help with high-stakes work if you verify."}$$,
   $$medium$$),
  (13, $$To get better output from an AI tool, the chapter suggests:$$,
   $$[{"id": "a", "text": "Giving it as little context as possible"}, {"id": "b", "text": "Prompting clearly and giving it the relevant context, since it can only work with what you provide"}, {"id": "c", "text": "Asking the same question repeatedly"}, {"id": "d", "text": "Using the longest possible prompt regardless of relevance"}]$$,
   $$b$$,
   $${"a": "Less context means weaker output.", "c": "Repetition doesn't improve a single answer.", "d": "Relevant context matters, not sheer length."}$$,
   $$medium$$),
  (14, $$When AI summarises a stakeholder document for you, you should:$$,
   $$[{"id": "a", "text": "Forward the summary as fact"}, {"id": "b", "text": "Spot-check it against the source, since summaries can drop nuance or introduce subtle errors"}, {"id": "c", "text": "Assume it captured everything"}, {"id": "d", "text": "Delete the original"}]$$,
   $$b$$,
   $${"a": "Forwarding unverified summaries risks passing on errors.", "c": "Summaries can miss or distort nuance.", "d": "Keep the source to verify against."}$$,
   $$medium$$),
  (15, $$Disclosure/transparency about AI use is appropriate when:$$,
   $$[{"id": "a", "text": "Never — always hide it"}, {"id": "b", "text": "It is relevant — e.g. being honest about how something was produced where that matters to the audience or the norms of your organisation"}, {"id": "c", "text": "Only when caught"}, {"id": "d", "text": "Always, in every sentence"}]$$,
   $$b$$,
   $${"a": "Concealment isn't the norm advised.", "c": "Proactive honesty beats disclosure-when-caught.", "d": "Constant disclosure isn't required; relevance is the guide."}$$,
   $$medium$$),
  (16, $$The efficiency gains from AI are real, but the chapter stresses that:$$,
   $$[{"id": "a", "text": "They eliminate the need for judgement"}, {"id": "b", "text": "The judgement layer — deciding what's right, accurate, and appropriate to send — remains yours"}, {"id": "c", "text": "They make accountability collective"}, {"id": "d", "text": "They remove the need to understand the work"}]$$,
   $$b$$,
   $${"a": "Judgement is exactly what stays human.", "c": "Accountability stays individual.", "d": "Understanding is still required."}$$,
   $$medium$$),
  (17, $$Relying on AI as a crutch that erodes your own skill is a risk because:$$,
   $$[{"id": "a", "text": "AI never makes mistakes"}, {"id": "b", "text": "If your underlying skill atrophies, you lose the ability to judge when the tool is wrong"}, {"id": "c", "text": "It is faster than learning"}, {"id": "d", "text": "It is always more accurate than you"}]$$,
   $$b$$,
   $${"a": "AI does make mistakes, which is why your skill matters.", "c": "Speed doesn't offset lost judgement.", "d": "It isn't reliably more accurate."}$$,
   $$medium$$),
  (18, $$A good test before sending AI-assisted work is:$$,
   $$[{"id": "a", "text": "Did the AI sound confident?"}, {"id": "b", "text": "Have I verified the claims and am I willing to stand behind this as my own work?"}, {"id": "c", "text": "Was it generated quickly?"}, {"id": "d", "text": "Is it long enough?"}]$$,
   $$b$$,
   $${"a": "Confidence isn't correctness.", "c": "Speed is irrelevant to quality.", "d": "Length is irrelevant to quality."}$$,
   $$medium$$),
  (19, $$Pasting a confidential vendor contract into a public AI tool to summarise it is:$$,
   $$[{"id": "a", "text": "Fine, because summaries are harmless"}, {"id": "b", "text": "A confidentiality breach risk — sensitive data shouldn't go into tools not approved for it, regardless of how useful the summary would be"}, {"id": "c", "text": "Fine if you delete the chat after"}, {"id": "d", "text": "Required for efficiency"}]$$,
   $$b$$,
   $${"a": "The risk is the input, not the summary.", "c": "Deleting the chat doesn't undo the exposure.", "d": "Efficiency doesn't justify the breach."}$$,
   $$medium$$),
  (20, $$The underlying principle of AI tool judgement is:$$,
   $$[{"id": "a", "text": "Let the tool do the work and the thinking"}, {"id": "b", "text": "Use the tool to amplify your work, but keep verification, confidentiality, judgement, and accountability with you"}, {"id": "c", "text": "Avoid the tool to stay safe"}, {"id": "d", "text": "Trust the tool more as it improves"}]$$,
   $$b$$,
   $${"a": "The thinking and accountability stay with you.", "c": "Avoidance forfeits real value.", "d": "Even improving tools require human verification."}$$,
   $$hard$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'using-ai'
on conflict do nothing;
