-- Seed 20 quiz items for Lesson 16 (escalation). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'escalation');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'escalation_judgment', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$In the chapter's year-two story, the escalation was wrong because the coordinator:$$,
   $$[{"id": "a", "text": "Waited too long to raise it"}, {"id": "b", "text": "Went over the PM's head to the PMO director — bypassing the natural chain and implying distrust of the PM's judgment"}, {"id": "c", "text": "Used overly soft language"}, {"id": "d", "text": "Escalated to the wrong external party"}]$$,
   $$b$$,
   $${"a": "It was raised repeatedly; the failure was the bypass.", "c": "The wording was 'professional'; the channel was the problem.", "d": "The PMO was internal; the issue was going around the PM."}$$,
   $$medium$$),
  (2, $$The PM was 'disappointed' (worse than furious) primarily because:$$,
   $$[{"id": "a", "text": "The email had a typo"}, {"id": "b", "text": "He'd been working the issue with the stakeholder's manager for three weeks, and the bypass signalled the coordinator didn't trust his judgment"}, {"id": "c", "text": "The issue wasn't real"}, {"id": "d", "text": "The sponsor was cc'd"}]$$,
   $$b$$,
   $${"a": "Not about a typo.", "c": "The issue was real; the handling was the problem.", "d": "It went to the PMO director, and the trust damage was the core."}$$,
   $$medium$$),
  (3, $$The chapter's year-six story (the vendor issue) was a failure of:$$,
   $$[{"id": "a", "text": "Over-escalation"}, {"id": "b", "text": "Under-escalation — staying passive on a serious, fixable problem while the overloaded PM waited for someone to insist on action"}, {"id": "c", "text": "Using dramatic language"}, {"id": "d", "text": "Bypassing the PM"}]$$,
   $$b$$,
   $${"a": "The opposite — the coordinator didn't push enough.", "c": "There was no escalation at all to be dramatic.", "d": "The coordinator stayed within the chain — too quietly."}$$,
   $$medium$$),
  (4, $$Escalation is defined as:$$,
   $$[{"id": "a", "text": "Complaining about a colleague"}, {"id": "b", "text": "Raising an issue to a higher level of authority than the one currently handling it"}, {"id": "c", "text": "Sending a status report"}, {"id": "d", "text": "Logging a risk"}]$$,
   $$b$$,
   $${"a": "That's the worst-case political version, not the definition.", "c": "Status reporting is routine, not escalation.", "d": "That's the RAID log."}$$,
   $$easy$$),
  (5, $$The difference between a good and a bad escalation is usually:$$,
   $$[{"id": "a", "text": "Whether it should have happened at all"}, {"id": "b", "text": "How it is handled — a clean escalation keeps the right people informed, follows the right channels, and is proportionate"}, {"id": "c", "text": "How loud it is"}, {"id": "d", "text": "Whether it goes to the sponsor"}]$$,
   $$b$$,
   $${"a": "Even appropriate escalations done badly damage relationships.", "c": "Volume isn't the discriminator.", "d": "The target depends on the issue, not on quality."}$$,
   $$medium$$),
  (6, $$The appropriateness test asks:$$,
   $$[{"id": "a", "text": "Is the recipient senior enough?"}, {"id": "b", "text": "Does this actually require a higher authority, or could the current level resolve it with more time, information, or pressure — and have they been given the chance?"}, {"id": "c", "text": "Is the email well-written?"}, {"id": "d", "text": "Will it make me look proactive?"}]$$,
   $$b$$,
   $${"a": "That's closer to the proportion test.", "c": "Quality of writing isn't the appropriateness test.", "d": "Self-image is irrelevant to whether escalation is warranted."}$$,
   $$medium$$),
  (7, $$The channels test asks:$$,
   $$[{"id": "a", "text": "Is the issue serious enough?"}, {"id": "b", "text": "Am I going through the right path — does the escalation target know, and am I avoiding bypassing the natural chain (e.g. going to the sponsor without the PM)?"}, {"id": "c", "text": "How many people should I cc?"}, {"id": "d", "text": "What colour is the RAG?"}]$$,
   $$b$$,
   $${"a": "That's the appropriateness/proportion tests.", "c": "Cc count isn't the test.", "d": "Unrelated to channels."}$$,
   $$medium$$),
  (8, $$The proportion test asks:$$,
   $$[{"id": "a", "text": "Is the seriousness of my concern proportionate to the level I'm escalating to?"}, {"id": "b", "text": "How long has it been open?"}, {"id": "c", "text": "Who is to blame?"}, {"id": "d", "text": "Is it on the critical path?"}]$$,
   $$a$$,
   $${"b": "Duration isn't proportion.", "c": "Blame isn't the test.", "d": "Criticality informs seriousness but isn't the proportion question itself."}$$,
   $$medium$$),
  (9, $$The first rung of the escalation ladder is:$$,
   $$[{"id": "a", "text": "The sponsor"}, {"id": "b", "text": "A direct conversation with the person involved"}, {"id": "c", "text": "The PMO"}, {"id": "d", "text": "Your PM"}]$$,
   $$b$$,
   $${"a": "That's a high rung, used for project-objective issues.", "c": "A formal route, not the first move.", "d": "Your PM is a later rung if the issue needs project-level response."}$$,
   $$easy$$),
  (10, $$The discipline of the escalation ladder is to:$$,
   $$[{"id": "a", "text": "Go as high as possible for maximum impact"}, {"id": "b", "text": "Use the lowest rung that will work — escalation is a search for the level that can actually resolve the issue, not a race to the top"}, {"id": "c", "text": "Always go to the sponsor"}, {"id": "d", "text": "Skip the person involved to save time"}]$$,
   $$b$$,
   $${"a": "Going high needlessly squanders relationships.", "c": "Sponsor-level is for objective-level issues only.", "d": "The direct conversation is the first rung for a reason."}$$,
   $$medium$$),
  (11, $$A good escalation information packet contains:$$,
   $$[{"id": "a", "text": "Just a request for help"}, {"id": "b", "text": "The situation (facts/dates), the impact, what's been tried, what's being asked, and the options"}, {"id": "c", "text": "A full transcript of every meeting"}, {"id": "d", "text": "The complete project plan"}]$$,
   $$b$$,
   $${"a": "A vague ask gets a vague response.", "c": "Transcripts aren't useful; a half-page is.", "d": "The whole plan buries the signal."}$$,
   $$medium$$),
  (12, $$'The situation' in an escalation packet should read:$$,
   $$[{"id": "a", "text": "'The vendor is being difficult'"}, {"id": "b", "text": "'The vendor has missed three of the last four weekly deliverables; the specific items and dates are X, Y, Z'"}, {"id": "c", "text": "'Things are going badly'"}, {"id": "d", "text": "'We have concerns'"}]$$,
   $$b$$,
   $${"a": "Too vague to act on.", "c": "No specifics.", "d": "No facts or dates."}$$,
   $$medium$$),
  (13, $$'What is being asked' should be:$$,
   $$[{"id": "a", "text": "'We need help'"}, {"id": "b", "text": "Specific — 'we need your intervention with the vendor's executive sponsor to secure a staffing commitment by next Friday'"}, {"id": "c", "text": "'Please advise'"}, {"id": "d", "text": "Left for the recipient to figure out"}]$$,
   $$b$$,
   $${"a": "A vague ask gets ignored.", "c": "'Please advise' invites no specific action.", "d": "You name the specific ask."}$$,
   $$medium$$),
  (14, $$The escalation packet should be about:$$,
   $$[{"id": "a", "text": "Ten pages with full detail"}, {"id": "b", "text": "Half a page — about five short paragraphs; if you can't describe it that briefly, think more before escalating"}, {"id": "c", "text": "A single sentence"}, {"id": "d", "text": "Whatever length the recipient prefers"}]$$,
   $$b$$,
   $${"a": "Senior readers want signal, not volume.", "c": "One sentence omits impact, options, and what's been tried.", "d": "The half-page discipline applies regardless."}$$,
   $$medium$$),
  (15, $$Which escalation language does the chapter recommend?$$,
   $$[{"id": "a", "text": "'Catastrophic,' 'disaster,' 'crisis,' 'failing'"}, {"id": "b", "text": "'At risk,' 'behind plan,' 'material exposure,' 'needs intervention'"}, {"id": "c", "text": "'Unacceptable' and 'incompetent'"}, {"id": "d", "text": "Whatever conveys the most urgency"}]$$,
   $$b$$,
   $${"a": "Those raise temperature without adding information.", "c": "Blame-laden and unprofessional.", "d": "Drama undermines seriousness with senior readers."}$$,
   $$medium$$),
  (16, $$The chapter's 'forwarding test' for escalation tone is:$$,
   $$[{"id": "a", "text": "Would my PM approve the formatting?"}, {"id": "b", "text": "Would I be comfortable if this exact text were forwarded to the person being discussed? (Escalations frequently get forwarded — write as if it's certain.)"}, {"id": "c", "text": "Is it under half a page?"}, {"id": "d", "text": "Does it name the critical path?"}]$$,
   $$b$$,
   $${"a": "Formatting isn't the test.", "c": "Length is a separate discipline.", "d": "Unrelated to the forwarding test."}$$,
   $$medium$$),
  (17, $$When an escalation does NOT work, what should you NOT do?$$,
   $$[{"id": "a", "text": "Escalate further with new information"}, {"id": "b", "text": "Keep raising the same issue to the same level hoping for a different response — it makes you look obsessive"}, {"id": "c", "text": "Accept the situation and manage within it"}, {"id": "d", "text": "Revisit whether the issue is as serious as you thought"}]$$,
   $$b$$,
   $${"a": "That's a valid next move (go higher / new info).", "c": "A legitimate option.", "d": "A legitimate option — re-examining your own analysis."}$$,
   $$medium$$),
  (18, $$After any escalation, the chapter says to:$$,
   $$[{"id": "a", "text": "Move on immediately"}, {"id": "b", "text": "Follow up — confirm what was decided, thank anyone who helped, and update the RAID log and status report to reflect the new state"}, {"id": "c", "text": "Delete the email trail"}, {"id": "d", "text": "Escalate again to be safe"}]$$,
   $$b$$,
   $${"a": "Unclosed escalations become confusing artifacts later.", "c": "You preserve the record, not delete it.", "d": "Re-escalating without new content is the obsessive anti-pattern."}$$,
   $$medium$$),
  (19, $$Escalating 'across' (engaging a peer's manager in a different reporting line) is:$$,
   $$[{"id": "a", "text": "Simpler than escalating up your own line"}, {"id": "b", "text": "More sensitive — it can feel like a complaint; the move is almost always through your PM, and you never surprise the PM with an email they didn't know was coming"}, {"id": "c", "text": "Best done directly and quietly"}, {"id": "d", "text": "Never appropriate"}]$$,
   $$b$$,
   $${"a": "It's more sensitive, not simpler.", "c": "Going directly/quietly across is exactly what to avoid; route through the PM.", "d": "It's sometimes needed — handled through the PM."}$$,
   $$medium$$),
  (20, $$At its best, escalation is:$$,
   $$[{"id": "a", "text": "A political move to get a different answer"}, {"id": "b", "text": "A disciplined use of the organisation's decision hierarchy — engaging the right higher level, giving them what they need, and empowering them to act"}, {"id": "c", "text": "A way to share blame"}, {"id": "d", "text": "A last resort that always damages relationships"}]$$,
   $$b$$,
   $${"a": "That's escalation at its worst.", "c": "It's about resolution, not blame-sharing.", "d": "A clean escalation usually does NOT damage relationships."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'escalation'
on conflict do nothing;
