-- Seed 20 quiz items for Lesson 13 (status-reports). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'status-reports');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'status_report_craft', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$In the chapter's 'report that got me promoted' story, the report worked because it:$$,
   $$[{"id": "a", "text": "Was longer and more detailed than the previous ones"}, {"id": "b", "text": "Stated plainly where the program was (amber, specific slips, decisions needed) in about a page — the sponsor 'finally understood what's happening'"}, {"id": "c", "text": "Stayed green to keep the sponsor calm"}, {"id": "d", "text": "Avoided naming any risks"}]$$,
   $$b$$,
   $${"a": "It was SHORTER — about a page vs four.", "c": "It went amber honestly; that's why it built trust.", "d": "It named three emerged risks and how each was managed."}$$,
   $$medium$$),
  (2, $$'Three audiences, three reports' refers to:$$,
   $$[{"id": "a", "text": "Three separate documents written from scratch"}, {"id": "b", "text": "The delivery team (operational detail), the PM/immediate stakeholders (tactical), and the sponsor/SC (strategic signal)"}, {"id": "c", "text": "Past, present, and future status"}, {"id": "d", "text": "Green, amber, and red reports"}]$$,
   $$b$$,
   $${"a": "It's one body of facts packaged three ways, not three from scratch.", "c": "The three are audiences, not timeframes.", "d": "Those are RAG colours, not audiences."}$$,
   $$medium$$),
  (3, $$The sponsor / steering committee primarily needs:$$,
   $$[{"id": "a", "text": "Full operational detail of who is doing what"}, {"id": "b", "text": "Strategic situational awareness — are we on track, major risks, what decisions are needed from them"}, {"id": "c", "text": "The complete RAID log"}, {"id": "d", "text": "A daily standup summary"}]$$,
   $$b$$,
   $${"a": "That's the delivery team's need; detail overwhelms the sponsor.", "c": "They need the 3–5 that matter, not the whole log.", "d": "Standup detail is for the team, not the sponsor."}$$,
   $$medium$$),
  (4, $$Producing one report for all three audiences is:$$,
   $$[{"id": "a", "text": "The efficient best practice"}, {"id": "b", "text": "Almost always wrong — detail overwhelms the sponsor, the sponsor summary is too thin for the team"}, {"id": "c", "text": "Fine if it's long enough"}, {"id": "d", "text": "Required for consistency"}]$$,
   $$b$$,
   $${"a": "It's the common mistake, not best practice.", "c": "Length doesn't fix the wrong register for each end.", "d": "Consistency comes from one source of facts, packaged differently."}$$,
   $$medium$$),
  (5, $$The recommended way to serve three audiences is to:$$,
   $$[{"id": "a", "text": "Write three independent reports"}, {"id": "b", "text": "Maintain one body of source facts and package it three ways for each audience"}, {"id": "c", "text": "Send everyone the tactical report"}, {"id": "d", "text": "Let each audience write their own"}]$$,
   $$b$$,
   $${"a": "That's wasteful; derive them from one source.", "c": "The tactical report is the wrong shape for the team and the sponsor.", "d": "You produce and shape the picture, not delegate it."}$$,
   $$medium$$),
  (6, $$The tactical status report's six sections, in order, are:$$,
   $$[{"id": "a", "text": "Headline; overall RAG; workstream status; key decisions/asks; risks & issues; upcoming"}, {"id": "b", "text": "Introduction; background; analysis; conclusion; appendix; sign-off"}, {"id": "c", "text": "Risks; budget; scope; schedule; quality; closure"}, {"id": "d", "text": "Whatever order fits the week"}]$$,
   $$a$$,
   $${"b": "That's an essay structure, not a status report.", "c": "Those are project variables, not report sections.", "d": "The order is deliberate because readers scan from the top."}$$,
   $$medium$$),
  (7, $$The headline of a status report should:$$,
   $$[{"id": "a", "text": "Be saved for the end after all the detail"}, {"id": "b", "text": "Summarise where the project is in 1–2 sentences, so a reader who reads nothing else still knows the state"}, {"id": "c", "text": "List every workstream"}, {"id": "d", "text": "Be a motivational message"}]$$,
   $$b$$,
   $${"a": "It goes first — though you often WRITE it last, once you know what the report says.", "c": "That's the workstream section, not the headline.", "d": "It's a factual summary, not a pep line."}$$,
   $$easy$$),
  (8, $$On RAG colours, the chapter says to use:$$,
   $$[{"id": "a", "text": "A five-colour scale for precision"}, {"id": "b", "text": "Just three — green, amber, red; no yellow, purple, or clever schemes"}, {"id": "c", "text": "Percentages instead of colours"}, {"id": "d", "text": "Whatever colours look good on the slide"}]$$,
   $$b$$,
   $${"a": "More colours add confusion, not precision.", "c": "RAG is a colour assessment with a sentence of rationale.", "d": "Everyone knows the three standard colours; stick to them."}$$,
   $$easy$$),
  (9, $$The 'Key decisions and asks' section should be:$$,
   $$[{"id": "a", "text": "Implicit — readers will infer what you need"}, {"id": "b", "text": "Explicit — pending decisions, escalations, overdue inputs, stated clearly; vague asks get ignored"}, {"id": "c", "text": "Omitted to keep the report short"}, {"id": "d", "text": "A list of everything the team is doing"}]$$,
   $$b$$,
   $${"a": "Implicit asks get missed — be explicit.", "c": "It's one of the highest-value sections; don't cut it.", "d": "It's what you need FROM readers, not a task list."}$$,
   $$medium$$),
  (10, $$The Risks & Issues section of a status report should contain:$$,
   $$[{"id": "a", "text": "The entire RAID log"}, {"id": "b", "text": "The 3–5 items that matter most — where attention would be useful"}, {"id": "c", "text": "Only risks that are already resolved"}, {"id": "d", "text": "No risks, to keep the tone positive"}]$$,
   $$b$$,
   $${"a": "The full log belongs in the RAID artifact, not the report.", "c": "Resolved risks don't need attention.", "d": "Hiding risks is color-washing — the worst failure mode."}$$,
   $$medium$$),
  (11, $$'We are navigating some challenges with vendor delivery' is an example of:$$,
   $$[{"id": "a", "text": "Appropriate diplomatic phrasing"}, {"id": "b", "text": "Euphemism — say 'the vendor has missed two deliverables in three weeks'; experienced readers read euphemism as distrust-inducing"}, {"id": "c", "text": "False precision"}, {"id": "d", "text": "A buried lede"}]$$,
   $$b$$,
   $${"a": "Euphemism erodes trust, it isn't diplomacy.", "c": "False precision is about fake numbers, not soft words.", "d": "A buried lede is about placement, not euphemism."}$$,
   $$medium$$),
  (12, $$Why is 'color washing' (everything green) the most damaging failure mode?$$,
   $$[{"id": "a", "text": "Green is hard to print"}, {"id": "b", "text": "It trains readers not to believe the report — twelve weeks of green is a badly reported project, not a well-run one"}, {"id": "c", "text": "It uses too much ink"}, {"id": "d", "text": "Sponsors prefer amber"}]$$,
   $$b$$,
   $${"a": "Printing isn't the issue.", "c": "The damage is to credibility, not ink.", "d": "Sponsors prefer green — which is exactly the pressure to resist."}$$,
   $$medium$$),
  (13, $$'Resource availability remains a risk' is criticised as:$$,
   $$[{"id": "a", "text": "Too specific"}, {"id": "b", "text": "A generic risk — always true on every project; if it's your worst risk you haven't thought hard enough"}, {"id": "c", "text": "A non-functional requirement"}, {"id": "d", "text": "An appropriate top risk"}]$$,
   $$b$$,
   $${"a": "It's the opposite — far too generic.", "c": "Wrong artifact entirely.", "d": "It's filler, not a real top risk."}$$,
   $$medium$$),
  (14, $$The chapter's test for every sentence in a status report is:$$,
   $$[{"id": "a", "text": "Is it grammatically correct?"}, {"id": "b", "text": "Does this tell a reader something specific they did not already know? If not, it's probably filler"}, {"id": "c", "text": "Is it positive in tone?"}, {"id": "d", "text": "Does it use the word 'shall'?"}]$$,
   $$b$$,
   $${"a": "Grammar matters but isn't the test.", "c": "Truthful, not positive, is the bar.", "d": "That's requirements phrasing, irrelevant here."}$$,
   $$medium$$),
  (15, $$'Amber' on a RAG rating means:$$,
   $$[{"id": "a", "text": "On track to meet objectives; no senior attention needed"}, {"id": "b", "text": "Something is at risk — identified exposure that warrants attention; the project may still meet its objectives"}, {"id": "c", "text": "Not on track; a material change is required"}, {"id": "d", "text": "The project is cancelled"}]$$,
   $$b$$,
   $${"a": "That's green.", "c": "That's red.", "d": "Amber is a warning, not cancellation."}$$,
   $$medium$$),
  (16, $$'Red' on a RAG rating means:$$,
   $$[{"id": "a", "text": "A minor wobble that will self-correct"}, {"id": "b", "text": "The project is not on track to meet one or more objectives with the current plan — a material change (scope/schedule/cost/method) and senior action are required"}, {"id": "c", "text": "Senior awareness is appropriate but action probably isn't"}, {"id": "d", "text": "Everything is fine"}]$$,
   $$b$$,
   $${"a": "Red is material, not a self-correcting wobble.", "c": "That's amber.", "d": "That's green."}$$,
   $$medium$$),
  (17, $$The chapter's 'courage move' on RAG ratings is:$$,
   $$[{"id": "a", "text": "Staying green as long as possible"}, {"id": "b", "text": "Going amber EARLY — early amber leaves time to act; late amber or a green-to-red jump means the project has been flying blind"}, {"id": "c", "text": "Jumping straight to red for impact"}, {"id": "d", "text": "Letting the sponsor pick the colour"}]$$,
   $$b$$,
   $${"a": "Drifting on green is the failure, not the move.", "c": "You escalate proportionately; the point is early amber.", "d": "The PM owns the rating, informed by your operational view."}$$,
   $$medium$$),
  (18, $$Who typically sets the RAG rating, and what's the coordinator's role?$$,
   $$[{"id": "a", "text": "The coordinator sets it unilaterally"}, {"id": "b", "text": "The PM sets it, but the coordinator drafts the first rating and has the clearest operational view — raise it directly if you think it should be amber"}, {"id": "c", "text": "The sponsor sets it"}, {"id": "d", "text": "It's set automatically by the schedule tool"}]$$,
   $$b$$,
   $${"a": "The PM owns it; the coordinator informs.", "c": "The sponsor receives it, not sets.", "d": "It's a judgement call, not a tool output."}$$,
   $$medium$$),
  (19, $$An efficient weekly status workflow starts on Monday with:$$,
   $$[{"id": "a", "text": "Writing the full report from memory"}, {"id": "b", "text": "Sending each workstream lead a short template: RAG this week, one sentence on what happened, one on what's coming"}, {"id": "c", "text": "Asking the sponsor what colour to use"}, {"id": "d", "text": "Building a new Gantt chart"}]$$,
   $$b$$,
   $${"a": "You gather inputs first, then write.", "c": "The sponsor receives the report; doesn't pre-set it.", "d": "That's not the status workflow."}$$,
   $$medium$$),
  (20, $$When consolidating workstream inputs against the schedule, RAID log, and action tracker, disagreements should be:$$,
   $$[{"id": "a", "text": "Reported as-is — just pass on what the leads said"}, {"id": "b", "text": "Clarified with the workstream lead before writing — this is the honesty step that keeps the report from becoming a polite fiction"}, {"id": "c", "text": "Averaged together"}, {"id": "d", "text": "Ignored"}]$$,
   $$b$$,
   $${"a": "Passing on unverified inputs is how reports lie.", "c": "You reconcile against evidence, not average.", "d": "The disagreement is exactly the signal to chase down."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'status-reports'
on conflict do nothing;
