-- Seed 20 quiz items for Lesson 23 (remote-hybrid). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'remote-hybrid');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'distributed_coordination', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$What does distributed work remove that the coordinator must deliberately replace?$$,
   $$[{"id": "a", "text": "The need for any documentation"}, {"id": "b", "text": "The ambient, hallway awareness that co-located teams get for free — so it must be recreated through deliberate written communication"}, {"id": "c", "text": "The project schedule"}, {"id": "d", "text": "The need for a PM"}]$$,
   $$b$$,
   $${"a": "Distributed work needs MORE documentation, not less.", "c": "The schedule still exists.", "d": "The PM role doesn't disappear."}$$,
   $$medium$$),
  (2, $$The chapter's default communication mode for distributed teams is:$$,
   $$[{"id": "a", "text": "Synchronous meetings for everything"}, {"id": "b", "text": "Async-first and written — so people across time zones can act without waiting for a live conversation"}, {"id": "c", "text": "Phone calls only"}, {"id": "d", "text": "Whatever is fastest for you"}]$$,
   $$b$$,
   $${"a": "Meeting-for-everything burdens time zones and overloads calendars.", "c": "Calls are ephemeral and zone-bound.", "d": "It centres on the distributed team, not your convenience."}$$,
   $$medium$$),
  (3, $$'Making work visible' across a distributed team means:$$,
   $$[{"id": "a", "text": "Telling people in person"}, {"id": "b", "text": "Putting status, decisions, and progress in shared, durable places — not locked in chat threads, calls, or one person's head"}, {"id": "c", "text": "Keeping updates in DMs"}, {"id": "d", "text": "Waiting to be asked"}]$$,
   $$b$$,
   $${"a": "In-person doesn't reach a distributed team.", "c": "DMs hide information from those who need it.", "d": "Visibility is proactive."}$$,
   $$medium$$),
  (4, $$Time-zone fairness, per the chapter, means:$$,
   $$[{"id": "a", "text": "Always meeting at your local working hours"}, {"id": "b", "text": "Rotating meeting times and not repeatedly burdening one region with unsociable hours"}, {"id": "c", "text": "Never meeting live"}, {"id": "d", "text": "Letting the most senior region set all times"}]$$,
   $$b$$,
   $${"a": "Anchoring to your zone offloads the cost onto others.", "c": "Some sync time is still valuable; the point is to share the burden.", "d": "Seniority shouldn't dictate who suffers the odd hours."}$$,
   $$medium$$),
  (5, $$Writing decisions down promptly matters more on a distributed team because:$$,
   $$[{"id": "a", "text": "It looks more professional"}, {"id": "b", "text": "People in other time zones need to act on the decision without waiting hours for you to be online to explain it"}, {"id": "c", "text": "It is required by law"}, {"id": "d", "text": "It replaces the need for any meetings"}]$$,
   $$b$$,
   $${"a": "The reason is unblocking others, not appearance.", "c": "It's good practice, not a legal duty.", "d": "It complements, not abolishes, sync time."}$$,
   $$medium$$),
  (6, $$In a hybrid meeting with some people in a room and some remote, the chapter warns that:$$,
   $$[{"id": "a", "text": "Remote attendees naturally dominate"}, {"id": "b", "text": "Remote attendees are easily disadvantaged — side conversations, body language, and whiteboards exclude them unless you level the field"}, {"id": "c", "text": "In-room attendees are always excluded"}, {"id": "d", "text": "Hybrid meetings work identically to in-person ones"}]$$,
   $$b$$,
   $${"a": "Remote people are typically disadvantaged, not dominant.", "c": "In-room people have the natural advantage.", "d": "They have distinct inclusion challenges."}$$,
   $$medium$$),
  (7, $$One way to level a hybrid meeting is to:$$,
   $$[{"id": "a", "text": "Let the room talk and have remote people listen"}, {"id": "b", "text": "Have everyone join individually on their own screen, or deliberately bring remote voices in and surface decisions in writing"}, {"id": "c", "text": "Stop inviting remote people"}, {"id": "d", "text": "Hold all decisions in the room only"}]$$,
   $$b$$,
   $${"a": "That entrenches the disadvantage.", "c": "Exclusion isn't inclusion.", "d": "In-room-only decisions cut remote people out."}$$,
   $$medium$$),
  (8, $$Because you cannot see distributed colleagues working, the chapter says to judge them by:$$,
   $$[{"id": "a", "text": "Hours visibly online / green status dots"}, {"id": "b", "text": "Outcomes and delivered work, not presence or activity signals"}, {"id": "c", "text": "How quickly they reply to chat"}, {"id": "d", "text": "Whether they attend every call"}]$$,
   $$b$$,
   $${"a": "Presence-policing is a failure mode.", "c": "Reply speed isn't productivity.", "d": "Attendance isn't output."}$$,
   $$medium$$),
  (9, $$'Presence policing' (treating remote workers with suspicion about whether they're really working) is:$$,
   $$[{"id": "a", "text": "A best practice for accountability"}, {"id": "b", "text": "A failure mode — it erodes trust and measures the wrong thing; coordinate by outcomes instead"}, {"id": "c", "text": "Required by most companies"}, {"id": "d", "text": "The only way to manage remote teams"}]$$,
   $$b$$,
   $${"a": "It's a failure mode, not best practice.", "c": "It's not a requirement.", "d": "Outcome-based coordination is the alternative."}$$,
   $$medium$$),
  (10, $$Spontaneous relationship-building doesn't happen remotely, so the coordinator should:$$,
   $$[{"id": "a", "text": "Accept that relationships will be weaker"}, {"id": "b", "text": "Build relationships deliberately — intentional check-ins and informal contact that co-location would have provided by accident"}, {"id": "c", "text": "Only build relationships in person"}, {"id": "d", "text": "Avoid non-work conversation entirely"}]$$,
   $$b$$,
   $${"a": "You compensate deliberately rather than accept decline.", "c": "Remote relationships can be built intentionally.", "d": "Some informal contact is exactly what's missing."}$$,
   $$medium$$),
  (11, $$The 'quiet drift' risk in distributed teams is that:$$,
   $$[{"id": "a", "text": "People talk too much"}, {"id": "b", "text": "Remote team members disengage or get blocked without it being visible, so you must actively check in rather than wait for problems to surface"}, {"id": "c", "text": "Meetings start late"}, {"id": "d", "text": "Documents drift out of date"}]$$,
   $$b$$,
   $${"a": "The risk is silence, not over-talking.", "c": "Lateness isn't the drift described.", "d": "That's a documentation issue, not the disengagement drift."}$$,
   $$medium$$),
  (12, $$Compared with co-located work, written clarity of ownership and next actions is:$$,
   $$[{"id": "a", "text": "Less important — people will figure it out"}, {"id": "b", "text": "More important — without hallway clarification, ambiguity stalls people for hours across zones"}, {"id": "c", "text": "Equally important"}, {"id": "d", "text": "Irrelevant if there's a chat channel"}]$$,
   $$b$$,
   $${"a": "Ambiguity is costlier when you can't tap someone's shoulder.", "c": "The cost of ambiguity rises with distance.", "d": "A chat channel doesn't substitute for explicit ownership."}$$,
   $$medium$$),
  (13, $$One failure mode is UNDER-communicating, which looks like:$$,
   $$[{"id": "a", "text": "Writing too many status updates"}, {"id": "b", "text": "Assuming distributed colleagues already know what you know, because you'd have mentioned it 'in the room' — but there is no room"}, {"id": "c", "text": "Rotating meeting times"}, {"id": "d", "text": "Documenting decisions"}]$$,
   $$b$$,
   $${"a": "That's over-communicating, the opposite pole.", "c": "That's good practice.", "d": "That's good practice."}$$,
   $$medium$$),
  (14, $$The opposite failure mode is OVER-meeting, which looks like:$$,
   $$[{"id": "a", "text": "Writing decisions down"}, {"id": "b", "text": "Trying to replace lost ambient context with a wall of sync calls — overloading calendars and time zones instead of writing things down"}, {"id": "c", "text": "Async-first communication"}, {"id": "d", "text": "Making work visible in shared docs"}]$$,
   $$b$$,
   $${"a": "That's the async-first remedy.", "c": "That's correct practice.", "d": "That's correct practice."}$$,
   $$medium$$),
  (15, $$Shared tools (boards, trackers, docs) function on a distributed team as:$$,
   $$[{"id": "a", "text": "Optional extras"}, {"id": "b", "text": "The shared source of truth — the durable place the team's state lives so anyone can see it regardless of time zone"}, {"id": "c", "text": "A substitute for doing the work"}, {"id": "d", "text": "Only useful for managers"}]$$,
   $$b$$,
   $${"a": "They're foundational, not optional.", "c": "They record the work, not replace it.", "d": "The whole team relies on them."}$$,
   $$medium$$),
  (16, $$When a decision is made on a live call with only part of the team present, you should:$$,
   $$[{"id": "a", "text": "Assume word will spread"}, {"id": "b", "text": "Write it up and post it where the absent members will see it, so the call doesn't create a knowledge gap by time zone"}, {"id": "c", "text": "Keep it among those who attended"}, {"id": "d", "text": "Re-run the whole meeting for each zone"}]$$,
   $$b$$,
   $${"a": "Word rarely spreads reliably across zones.", "c": "That creates exactly the gap to avoid.", "d": "A written summary is more efficient than re-running it."}$$,
   $$medium$$),
  (17, $$Over-communicating in writing on a distributed team is:$$,
   $$[{"id": "a", "text": "A nuisance to be avoided"}, {"id": "b", "text": "Often appropriate — a bit of redundancy in writing is cheaper than the cost of someone being blocked or out of the loop"}, {"id": "c", "text": "Always a sign of poor judgement"}, {"id": "d", "text": "Only acceptable for executives"}]$$,
   $$b$$,
   $${"a": "Reasonable written redundancy is a feature here.", "c": "It's a deliberate compensation, not poor judgement.", "d": "It serves the whole team."}$$,
   $$medium$$),
  (18, $$Why does trust matter even more on distributed teams?$$,
   $$[{"id": "a", "text": "Because you can monitor everyone closely"}, {"id": "b", "text": "Because you can't observe people working, so coordination relies on trusting commitments and verifying through outcomes, not surveillance"}, {"id": "c", "text": "Because remote workers are less reliable"}, {"id": "d", "text": "Because trust is irrelevant remotely"}]$$,
   $$b$$,
   $${"a": "Close monitoring is the wrong model.", "c": "The chapter rejects that assumption.", "d": "Trust is more central, not less."}$$,
   $$medium$$),
  (19, $$Respecting working hours across time zones means:$$,
   $$[{"id": "a", "text": "Expecting instant replies at all hours"}, {"id": "b", "text": "Not expecting people to be on-call outside their hours — using async so responses can come within their own working day"}, {"id": "c", "text": "Requiring everyone to shift to your schedule"}, {"id": "d", "text": "Banning all meetings"}]$$,
   $$b$$,
   $${"a": "Always-on expectations burn people out.", "c": "Shifting everyone to one zone is the unfairness to avoid.", "d": "Some sync is fine; the point is respecting hours."}$$,
   $$medium$$),
  (20, $$The underlying principle of distributed coordination is:$$,
   $$[{"id": "a", "text": "Recreate the office exactly over video"}, {"id": "b", "text": "Deliberately and explicitly provide the visibility, clarity, fairness, and trust that co-location would have supplied implicitly"}, {"id": "c", "text": "Minimise written communication"}, {"id": "d", "text": "Coordinate only with people in your own time zone"}]$$,
   $$b$$,
   $${"a": "You compensate for distance, not simulate the office.", "c": "Written communication is the backbone.", "d": "You coordinate across all zones fairly."}$$,
   $$hard$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'remote-hybrid'
on conflict do nothing;
