-- Seed 20 quiz items for Lesson 19 (reading-the-room). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'reading-the-room');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'political_intelligence', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$In the chapter's governance-review story, the program was descoped ~30% because:$$,
   $$[{"id": "a", "text": "The meeting reached an honest consensus"}, {"id": "b", "text": "The decision had effectively been made elsewhere — the PMO head pre-aligned with the sponsor beforehand; the meeting was largely theatre"}, {"id": "c", "text": "The numbers were bad"}, {"id": "d", "text": "The program manager argued for it"}]$$,
   $$b$$,
   $${"a": "The 'honest conversation' framing was surface; the real decision formed outside the room.", "c": "The PM's numbers were slightly better than reality; that wasn't the driver.", "d": "The PM argued for full funding and was surprised by the descope."}$$,
   $$medium$$),
  (2, $$The four channels a room communicates on are:$$,
   $$[{"id": "a", "text": "Email, Slack, phone, in-person"}, {"id": "b", "text": "Spoken, relational, temporal, and absence"}, {"id": "c", "text": "Red, amber, green, grey"}, {"id": "d", "text": "Scope, schedule, cost, risk"}]$$,
   $$b$$,
   $${"a": "Those are media, not the chapter's channels.", "c": "Those are RAG colours.", "d": "Project variables, not channels."}$$,
   $$medium$$),
  (3, $$The relational channel is:$$,
   $$[{"id": "a", "text": "What people literally say"}, {"id": "b", "text": "What people signal about their relationships — who they look to, defer to, echo, or interrupt; almost always honest because it's hard to fake"}, {"id": "c", "text": "What's deferred to a later meeting"}, {"id": "d", "text": "Who isn't in the room"}]$$,
   $$b$$,
   $${"a": "That's the spoken channel.", "c": "That's the temporal channel.", "d": "That's the absence channel."}$$,
   $$medium$$),
  (4, $$'Let's take that offline' or 'let's come back to that next time' is a signal on which channel?$$,
   $$[{"id": "a", "text": "Spoken"}, {"id": "b", "text": "Temporal — what's being saved for later often reveals what the room won't discuss in current company"}, {"id": "c", "text": "Absence"}, {"id": "d", "text": "Relational"}]$$,
   $$b$$,
   $${"a": "The deferral's meaning is temporal, not just the words.", "c": "Absence is about who/what is missing entirely.", "d": "Relational is about who-defers-to-whom."}$$,
   $$medium$$),
  (5, $$The absence channel refers to:$$,
   $$[{"id": "a", "text": "Who is the loudest in the room"}, {"id": "b", "text": "Who is NOT in the room and what is NOT being said — often the most revealing part of the scene"}, {"id": "c", "text": "The agenda items covered"}, {"id": "d", "text": "The official minutes"}]$$,
   $$b$$,
   $${"a": "Loudness is a spoken/relational signal.", "c": "What's covered is the spoken channel; absence is what's left out.", "d": "Minutes record the spoken channel."}$$,
   $$medium$$),
  (6, $$The spoken channel is described as:$$,
   $$[{"id": "a", "text": "The most reliable signal of intent"}, {"id": "b", "text": "The easiest to read but often the least informative, because people are careful about what they say"}, {"id": "c", "text": "Impossible to read"}, {"id": "d", "text": "Only relevant in writing"}]$$,
   $$b$$,
   $${"a": "It's the least informative, not the most reliable.", "c": "It's the easiest, not impossible.", "d": "It applies to spoken meetings too."}$$,
   $$medium$$),
  (7, $$When a second speaker echoes the first almost verbatim within a minute, it usually indicates:$$,
   $$[{"id": "a", "text": "Genuine independent agreement"}, {"id": "b", "text": "Pre-alignment — they've likely talked beforehand; not sinister, but notice who aligned with whom"}, {"id": "c", "text": "That they weren't listening"}, {"id": "d", "text": "A scheduling conflict"}]$$,
   $$b$$,
   $${"a": "Verbatim echo so fast usually isn't independent.", "c": "It's alignment, not inattention.", "d": "Unrelated."}$$,
   $$medium$$),
  (8, $$'Sounds fine,' said without energy, or silence in response to a proposal, is most often:$$,
   $$[{"id": "a", "text": "Genuine assent"}, {"id": "b", "text": "The unspoken no — withholding/dissent that will emerge later in a side channel"}, {"id": "c", "text": "Boredom"}, {"id": "d", "text": "Approval to proceed immediately"}]$$,
   $$b$$,
   $${"a": "Low-energy 'fine' is more often dissent than assent.", "c": "It reads as withholding, not boredom.", "d": "It's the opposite of clear approval."}$$,
   $$medium$$),
  (9, $$An 'indirect advocate' is someone who:$$,
   $$[{"id": "a", "text": "Argues their position loudly and directly"}, {"id": "b", "text": "Advances a position by asking questions that steer the conversation toward it, rather than arguing directly"}, {"id": "c", "text": "Stays completely silent"}, {"id": "d", "text": "Always agrees with the sponsor"}]$$,
   $$b$$,
   $${"a": "That's a direct advocate.", "c": "Silence is the unspoken no, not advocacy.", "d": "Agreeing isn't steering via questions."}$$,
   $$medium$$),
  (10, $$Quick, easy consensus on a genuinely contested topic often means:$$,
   $$[{"id": "a", "text": "The team is highly aligned and effective"}, {"id": "b", "text": "The room avoided the thing it disagrees on, rather than actually resolving it"}, {"id": "c", "text": "The decision was well-analysed"}, {"id": "d", "text": "Nothing in particular"}]$$,
   $$b$$,
   $${"a": "Agreement arriving too quickly is worth watching, not celebrating.", "c": "It can mask unresolved disagreement.", "d": "It's a meaningful signal to notice."}$$,
   $$medium$$),
  (11, $$A decision 'deferred for more analysis' sometimes actually means:$$,
   $$[{"id": "a", "text": "More analysis is genuinely needed"}, {"id": "b", "text": "The decision has been made elsewhere and is not being revisited in this room"}, {"id": "c", "text": "The sponsor is absent"}, {"id": "d", "text": "The project is cancelled"}]$$,
   $$b$$,
   $${"a": "Sometimes true — but it can also be a polite cover.", "c": "Deferral isn't about attendance.", "d": "It's a deferral, not a cancellation."}$$,
   $$medium$$),
  (12, $$A primary use of reading the room is to:$$,
   $$[{"id": "a", "text": "Win arguments for yourself"}, {"id": "b", "text": "Prepare your PM better — e.g. flag that a key stakeholder is misaligned so they can plan"}, {"id": "c", "text": "Record the politics in the minutes"}, {"id": "d", "text": "Take sides early"}]$$,
   $$b$$,
   $${"a": "It's used to help, not to advance yourself.", "c": "Political reads stay out of artifacts.", "d": "Staying out of the fight is the discipline."}$$,
   $$medium$$),
  (13, $$Matching your communication to a stakeholder who prefers options over recommendations means:$$,
   $$[{"id": "a", "text": "Always giving a single recommendation"}, {"id": "b", "text": "Offering options rather than a single recommendation — and briefing the surprise-averse in advance"}, {"id": "c", "text": "Withholding information"}, {"id": "d", "text": "Copying everyone on everything"}]$$,
   $$b$$,
   $${"a": "That ignores their preference.", "c": "Adjusting style isn't withholding.", "d": "Broadcasting isn't matching style."}$$,
   $$medium$$),
  (14, $$How should you track the political dynamics you observe over time?$$,
   $$[{"id": "a", "text": "In the RAID log"}, {"id": "b", "text": "Privately, in your own sense of the project — not in any artifact"}, {"id": "c", "text": "In the status report"}, {"id": "d", "text": "In the minutes"}]$$,
   $$b$$,
   $${"a": "Political reads don't go in the RAID log.", "c": "Not in the status report.", "d": "Not in the minutes."}$$,
   $$medium$$),
  (15, $$Coordinators who read the room well typically:$$,
   $$[{"id": "a", "text": "Become active participants in political conflicts"}, {"id": "b", "text": "Choose NOT to be drawn into political conflicts as participants — they observe without taking sides"}, {"id": "c", "text": "Side with the most powerful person"}, {"id": "d", "text": "Report everyone's positions to the sponsor"}]$$,
   $$b$$,
   $${"a": "Getting drawn in is the trap.", "c": "Allying with power is the manipulation failure.", "d": "Reporting positions around breaches trust."}$$,
   $$medium$$),
  (16, $$The chapter's internal test for the integrity line is:$$,
   $$[{"id": "a", "text": "Will this make me look smart?"}, {"id": "b", "text": "Am I using what I see to be more HELPFUL, or to be more ADVANTAGED? The first is the craft; the second is the trap"}, {"id": "c", "text": "Can I prove it?"}, {"id": "d", "text": "Will the sponsor approve?"}]$$,
   $$b$$,
   $${"a": "Self-image isn't the test.", "c": "Provability isn't the integrity test.", "d": "Approval isn't the test."}$$,
   $$hard$$),
  (17, $$Political intelligence, as the chapter defines it, is NOT:$$,
   $$[{"id": "a", "text": "Seeing accurately and using it to help the project and its people"}, {"id": "b", "text": "Manipulation, playing people off each other, or advancing by allying with the powerful"}, {"id": "c", "text": "Careful attention applied consistently"}, {"id": "d", "text": "Reading multiple channels at once"}]$$,
   $$b$$,
   $${"a": "That IS the craft the chapter describes.", "c": "That's exactly what it IS.", "d": "That's the skill itself."}$$,
   $$medium$$),
  (18, $$The coordinators who read rooms best tend to be:$$,
   $$[{"id": "a", "text": "Feared by everyone"}, {"id": "b", "text": "Trusted by people on multiple sides of political divides — because their reading isn't used to advance themselves at others' expense"}, {"id": "c", "text": "Allied only with the powerful"}, {"id": "d", "text": "Known for leaking information"}]$$,
   $$b$$,
   $${"a": "They're trusted, not feared.", "c": "Allying with power is the trap.", "d": "Leaking destroys the trust that makes the skill valuable."}$$,
   $$medium$$),
  (19, $$Reading the room is only valuable if it:$$,
   $$[{"id": "a", "text": "Is written up formally"}, {"id": "b", "text": "Informs what you actually do — changes how you or your PM act"}, {"id": "c", "text": "Is shared with the whole team"}, {"id": "d", "text": "Proves you right"}]$$,
   $$b$$,
   $${"a": "It stays out of formal artifacts.", "c": "It's a private read, not a team broadcast.", "d": "It's about being helpful, not being right."}$$,
   $$medium$$),
  (20, $$Political intelligence is fundamentally:$$,
   $$[{"id": "a", "text": "A manipulative trick"}, {"id": "b", "text": "Careful attention applied consistently — reading multiple channels at once, not a trick"}, {"id": "c", "text": "Innate charisma you either have or don't"}, {"id": "d", "text": "Only relevant for senior leaders"}]$$,
   $$b$$,
   $${"a": "The chapter explicitly rejects the manipulative framing.", "c": "It's a learnable discipline of attention.", "d": "Coordinators benefit from it too."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'reading-the-room'
on conflict do nothing;
