-- Seed 20 quiz items for Lesson 14 (change-requests). Hand-authored, grounded in the chapter.
-- Idempotent: clears this lesson's items first. Mirrors what was applied to prod via MCP.

delete from public.quiz_items
where lesson_id = (select id from public.lessons where slug = 'change-requests');

insert into public.quiz_items
  (lesson_id, sort, stem, options, correct, distractor_rationale, competency, difficulty, is_ai_generated)
select l.id, v.sort, v.stem, v.options::jsonb, v.correct, v.rationale::jsonb,
       'change_request_craft', v.difficulty, false
from public.lessons l
cross join (values
  (1, $$In 'the change process nobody used,' the process failed because it was:$$,
   $$[{"id": "a", "text": "Too loose — no controls at all"}, {"id": "b", "text": "Too heavy — sixteen fields, four approvers, a weekly board; the friction was so high everyone worked around it"}, {"id": "c", "text": "Too cheap to take seriously"}, {"id": "d", "text": "Run by the wrong person"}]$$,
   $$b$$,
   $${"a": "It was the opposite — comprehensive but unused.", "c": "Cost wasn't the issue; friction was.", "d": "Ownership wasn't the failure; weight was."}$$,
   $$medium$$),
  (2, $$The redesigned change process worked by:$$,
   $$[{"id": "a", "text": "Removing all approvals"}, {"id": "b", "text": "Tiering by magnitude — small changes a one-page PM approval; medium a fuller template logged but no board; large the full formal process"}, {"id": "c", "text": "Adding more approvers"}, {"id": "d", "text": "Banning all changes"}]$$,
   $$b$$,
   $${"a": "Tiered approval remained; it was proportionate, not absent.", "c": "More approvers would worsen the friction.", "d": "Changes are inevitable; the point is to track them."}$$,
   $$medium$$),
  (3, $$Why was the silent scope drift a problem (since changes are inevitable)?$$,
   $$[{"id": "a", "text": "The changes were technically wrong"}, {"id": "b", "text": "The drift was invisible — the sponsor believed the original scope, the budget didn't reflect the added work, and the plan was silently overcommitted"}, {"id": "c", "text": "The team worked too slowly"}, {"id": "d", "text": "There were too few changes"}]$$,
   $$b$$,
   $${"a": "The changes were fine; their invisibility was the problem.", "c": "It was performing adequately on a grown scope — but looked like underperformance.", "d": "Changes were happening; they just weren't logged."}$$,
   $$medium$$),
  (4, $$A change request is the formal mechanism for:$$,
   $$[{"id": "a", "text": "Reporting weekly status"}, {"id": "b", "text": "Proposing a change to something the project has baselined — scope, schedule, cost, resources, or approach"}, {"id": "c", "text": "Logging risks"}, {"id": "d", "text": "Assigning daily tasks"}]$$,
   $$b$$,
   $${"a": "That's the status report.", "c": "That's the RAID log.", "d": "That's the action tracker."}$$,
   $$easy$$),
  (5, $$The threefold purpose of a CR is to:$$,
   $$[{"id": "a", "text": "Slow the project down, create paperwork, and protect the PM"}, {"id": "b", "text": "Make the change visible, analyse its impact before committing, and route the decision to the right decider"}, {"id": "c", "text": "Reward the team, punish vendors, and satisfy audit"}, {"id": "d", "text": "Replace the schedule, budget, and RAID log"}]$$,
   $$b$$,
   $${"a": "It enables deliberate decisions, not bureaucracy.", "c": "None of those are the purpose.", "d": "It feeds those artifacts; it doesn't replace them."}$$,
   $$medium$$),
  (6, $$A CR is, at its core, about:$$,
   $$[{"id": "a", "text": "Paperwork and form-filling"}, {"id": "b", "text": "Deliberate decision-making on things that affect the project's baseline"}, {"id": "c", "text": "Keeping the change board busy"}, {"id": "d", "text": "Documenting blame"}]$$,
   $$b$$,
   $${"a": "The paperwork serves the decision, not the reverse.", "c": "The board exists for large changes only.", "d": "It records baseline evolution, not blame."}$$,
   $$medium$$),
  (7, $$The 'what is being changed' section should be:$$,
   $$[{"id": "a", "text": "General — 'we need more integration work'"}, {"id": "b", "text": "Specific — 'the integration scope will be expanded to include handling of X transaction type, per stakeholder request Y'"}, {"id": "c", "text": "Left blank until approval"}, {"id": "d", "text": "A list of who is to blame"}]$$,
   $$b$$,
   $${"a": "Vague descriptions invite later scope argument.", "c": "It must be specified to be analysed.", "d": "Attribution of blame isn't the content."}$$,
   $$medium$$),
  (8, $$A CR's impact analysis should address:$$,
   $$[{"id": "a", "text": "Only the cost"}, {"id": "b", "text": "All five variables — scope, schedule, cost, quality, risk — quantified where possible"}, {"id": "c", "text": "Only the schedule"}, {"id": "d", "text": "Just a yes/no recommendation"}]$$,
   $$b$$,
   $${"a": "Cost alone hides cascading effects.", "c": "Schedule alone is incomplete.", "d": "The recommendation is separate from the impact analysis."}$$,
   $$medium$$),
  (9, $$Why include 'alternatives considered,' even briefly?$$,
   $$[{"id": "a", "text": "To pad the document"}, {"id": "b", "text": "Future readers want to know the alternatives were genuinely considered, not just the chosen path"}, {"id": "c", "text": "To delay the decision"}, {"id": "d", "text": "It is never necessary"}]$$,
   $$b$$,
   $${"a": "It's substance, not padding.", "c": "It informs, not delays, the decision.", "d": "It's often thin but it matters."}$$,
   $$medium$$),
  (10, $$The tiered routing pattern for CRs is:$$,
   $$[{"id": "a", "text": "Everything goes to the steering committee"}, {"id": "b", "text": "PM-level for small changes; PM + sponsor for medium; steering committee for large (external commitments, major milestones, significant budget)"}, {"id": "c", "text": "The coordinator approves everything"}, {"id": "d", "text": "No approval needed for anything under budget"}]$$,
   $$b$$,
   $${"a": "Routing everything to the SC recreates the friction problem.", "c": "The coordinator routes and prepares, not approves.", "d": "Even small changes are logged and PM-approved."}$$,
   $$medium$$),
  (11, $$Vague change thresholds produce ___; clear thresholds produce ___:$$,
   $$[{"id": "a", "text": "flow; argument"}, {"id": "b", "text": "argument; flow"}, {"id": "c", "text": "speed; quality"}, {"id": "d", "text": "trust; risk"}]$$,
   $$b$$,
   $${"a": "Reversed — vague produces argument.", "c": "Not the contrast the chapter draws.", "d": "Not the contrast the chapter draws."}$$,
   $$medium$$),
  (12, $$The coordinator's role in CR routing typically includes:$$,
   $$[{"id": "a", "text": "Approving large changes"}, {"id": "b", "text": "Assessing the tier, preparing the analysis at the right depth, scheduling the review with the right approvers, and maintaining the change log"}, {"id": "c", "text": "Deciding whether the change is worth it"}, {"id": "d", "text": "Negotiating the budget with finance"}]$$,
   $$b$$,
   $${"a": "Approval authority sits with the PM/sponsor/SC.", "c": "That's the decider's job, not the coordinator's.", "d": "That's the PM/sponsor's negotiation."}$$,
   $$medium$$),
  (13, $$Change requests are often politically loaded because they:$$,
   $$[{"id": "a", "text": "Are always rejected"}, {"id": "b", "text": "Surface trade-offs stakeholders would prefer remained implicit — who pays, who loses a feature, what was committed and to whom"}, {"id": "c", "text": "Require legal review"}, {"id": "d", "text": "Are too technical for sponsors"}]$$,
   $$b$$,
   $${"a": "Many are approved; politics is about the trade-offs.", "c": "Only large/external ones touch legal.", "d": "The politics is about trade-offs, not technicality."}$$,
   $$medium$$),
  (14, $$The coordinator's role in the politics of a CR is to:$$,
   $$[{"id": "a", "text": "Resolve the politics themselves"}, {"id": "b", "text": "Prepare the CR so the trade-offs are visible and resolvable BEFORE the meeting, rather than erupting in it"}, {"id": "c", "text": "Hide the trade-offs to keep the meeting calm"}, {"id": "d", "text": "Take a side"}]$$,
   $$b$$,
   $${"a": "The PM and sponsor resolve the politics.", "c": "Hiding trade-offs makes them erupt at approval time.", "d": "The coordinator stays neutral."}$$,
   $$medium$$),
  (15, $$Which CRs go into the change log?$$,
   $$[{"id": "a", "text": "Only approved ones"}, {"id": "b", "text": "Every CR — approved, rejected, or deferred — as a permanent record of how the baseline evolved"}, {"id": "c", "text": "Only large ones"}, {"id": "d", "text": "Only ones with budget impact"}]$$,
   $$b$$,
   $${"a": "Rejected and deferred CRs are part of the record too.", "c": "All tiers are logged.", "d": "Scope/schedule-only changes are logged as well."}$$,
   $$easy$$),
  (16, $$A change log with zero entries six months into a project most likely means:$$,
   $$[{"id": "a", "text": "The project is exceptionally well-planned"}, {"id": "b", "text": "Changes are happening off the log — a project with no changes is one that didn't learn"}, {"id": "c", "text": "The project has no scope"}, {"id": "d", "text": "The log is required to be empty"}]$$,
   $$b$$,
   $${"a": "Zero changes is almost always a reporting gap, not excellence.", "c": "Every project has scope; this is about tracking change.", "d": "The log should reflect real changes."}$$,
   $$medium$$),
  (17, $$Typical scope growth through changes over a project's life is around:$$,
   $$[{"id": "a", "text": "0% — well-run projects don't change"}, {"id": "b", "text": "10–20% (with wide variation); ~50% is usually a red flag and 0% is almost always wrong"}, {"id": "c", "text": "Always exactly 50%"}, {"id": "d", "text": "Over 100%"}]$$,
   $$b$$,
   $${"a": "Zero growth signals changes happening off the books.", "c": "50% is a warning sign, not the norm.", "d": "That would indicate a runaway project."}$$,
   $$medium$$),
  (18, $$Years after a project, the change log is valuable in disputes because it:$$,
   $$[{"id": "a", "text": "Lists who attended each meeting"}, {"id": "b", "text": "Resolves 'what was agreed when?' — the change-log analog of the kickoff-minutes story"}, {"id": "c", "text": "Shows the team's velocity"}, {"id": "d", "text": "Contains the source code"}]$$,
   $$b$$,
   $${"a": "Attendance is in minutes, not the change log.", "c": "Velocity is a delivery metric.", "d": "It records baseline changes, not code."}$$,
   $$medium$$),
  (19, $$A project whose change log shows mostly schedule-extension CRs reveals:$$,
   $$[{"id": "a", "text": "Nothing useful"}, {"id": "b", "text": "A planning pattern — duration was likely underestimated"}, {"id": "c", "text": "That the team is lazy"}, {"id": "d", "text": "That scope was cut"}]$$,
   $$b$$,
   $${"a": "The log's patterns are a key learning source.", "c": "It's a planning signal, not a people judgement.", "d": "Extensions point to duration, not scope cuts."}$$,
   $$medium$$),
  (20, $$Change-log discipline means updating it:$$,
   $$[{"id": "a", "text": "Only at project closeout"}, {"id": "b", "text": "Every time a CR moves through a status — submitted, under review, approved, rejected, deferred, closed — with dates"}, {"id": "c", "text": "Once when the CR is first raised"}, {"id": "d", "text": "Whenever the sponsor asks"}]$$,
   $$b$$,
   $${"a": "It must be a living record, not a closeout exercise.", "c": "Each status transition is logged, not just the start.", "d": "It's maintained continuously, not on request."}$$,
   $$medium$$)
) as v(sort, stem, options, correct, rationale, difficulty)
where l.slug = 'change-requests'
on conflict do nothing;
