import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Validates the narrated-slides deck for each lesson under scripts/video/.
 *
 * Source of truth is the per-lesson Python segments.py; the committed
 * segments.json is its machine-readable export (regenerated by
 * render_slides.py / build_common.write_segments_json). We assert the deck's
 * invariants and the 1:1 mapping to the committed slides/NN.png files.
 */
const LESSONS_DIR = resolve(__dirname, "../../scripts/video/lessons");

type Segment = { id: number; mode: string; has_narration: boolean };

// Card templates (title/end) MAY hold 3s silent — e.g. the opening title and
// closing end card. They may also be narrated (a mid-deck title divider is).
// The load-bearing invariant is the reverse: every content slide is narrated.
const CARD_MODES = new Set(["title", "end"]);

const LESSONS = ["lesson-20-raid-logs"];

describe.each(LESSONS)("video segments: %s", (slug) => {
  const lessonDir = resolve(LESSONS_DIR, slug);
  const segments = JSON.parse(
    readFileSync(resolve(lessonDir, "segments.json"), "utf8")
  ) as Segment[];

  it("has at least one segment", () => {
    expect(segments.length).toBeGreaterThan(0);
  });

  it("ids are unique and strictly ascending", () => {
    const ids = segments.map((s) => s.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (let i = 1; i < ids.length; i++) {
      expect(ids[i]).toBeGreaterThan(ids[i - 1]);
    }
  });

  it("every content (non-card) segment has narration", () => {
    for (const s of segments) {
      if (CARD_MODES.has(s.mode)) continue;
      expect(s.has_narration, `slide ${s.id} (${s.mode}) needs narration`).toBe(true);
    }
  });

  it("only card-mode segments may be silent", () => {
    for (const s of segments) {
      if (!s.has_narration) {
        expect(CARD_MODES.has(s.mode), `silent slide ${s.id} is mode ${s.mode}`).toBe(true);
      }
    }
  });

  it("each segment id maps 1:1 to a committed slides/NN.png", () => {
    for (const s of segments) {
      const png = resolve(lessonDir, "slides", `${String(s.id).padStart(2, "0")}.png`);
      expect(existsSync(png), `missing ${png}`).toBe(true);
    }
  });
});
