// GENERATED by scripts/gen-template-sheets.mjs — one line per sheet of each
// starter workbook in public/templates (Workbook tab: "what goes in it").
// Regenerate after changing a template; hand-edit wording if needed.

export type TemplateSheet = { sheet: string; what: string };

export const TEMPLATE_SHEETS: Record<string, TemplateSheet[]> = {
  "/templates/coordinator_role_self_audit.xlsx": [
    {
      sheet: "Five Buckets",
      what: "Score yourself 1–5 on each bucket. Then pick ONE to work on for the next month.",
    },
    {
      sheet: "Inbox Audit",
      what: "Don't answer — audit. Look at the pattern of who is emailing you, what they want, how fast you reply.",
    },
    {
      sheet: "Role Clarity",
      what: "Place yourself in one of the three coordinator roles that share the job title.",
    },
  ],
  "/templates/five_variable_posture.xlsx": [
    {
      sheet: "Five Variables",
      what: "For each variable: how much flex is left, how committed it is, evidence on this project.",
    },
    {
      sheet: "Scope Triple",
      what: "For each scope question on your project, capture what's documented vs what the sponsor seems to expect.",
    },
    {
      sheet: "Risk Mapping",
      what: "For your top 10 risks, name which of the five variables would absorb the impact.",
    },
    {
      sheet: "Contingency",
      what: "Track contingency consumption month by month.",
    },
  ],
  "/templates/governance_reading_kit.xlsx": [
    {
      sheet: "Stated vs Actual",
      what: "For each item, capture the formal/stated structure on the left, what you've actually observed on the right, and the gap.",
    },
    {
      sheet: "Stakeholder Map",
      what: "For each named stakeholder, mark influence level and engagement level.",
    },
    {
      sheet: "Sponsor Diagnostic",
      what: "Mark the type. List the symptoms you're seeing.",
    },
    {
      sheet: "RACI Audit",
      what: "For each major decision type on your project, name who's R, A, C, I.",
    },
  ],
  "/templates/methodology_fit_diagnostic.xlsx": [
    {
      sheet: "Fit Diagnostic",
      what: "Score this project on each axis 1–5. Lean waterfall (left) ↔ Lean agile (right).",
    },
    {
      sheet: "Failure Spot-Check",
      what: "Mark Y/N for each of the five failure modes on your project, with evidence and your next step.",
    },
    {
      sheet: "Translation Map",
      what: "On a hybrid project, list the artifacts that flow between agile workstreams and waterfall governance — and who owns the translation.",
    },
  ],
  "/templates/mindset_practice_tracker.xlsx": [
    {
      sheet: "Seven Shifts",
      what: "Score yourself 1–5 on each. Be honest. Pick ONE to work on for 30 days.",
    },
    {
      sheet: "Daily Question",
      what: "The 6-week ownership practice. Every weekday, write the answer.",
    },
    {
      sheet: "Composure Log",
      what: "When something triggers a strong reaction at work — log it.",
    },
    {
      sheet: "Mistake Log",
      what: "When something goes wrong — log it cleanly.",
    },
  ],
  "/templates/project_lifecycle_phase_map.xlsx": [
    {
      sheet: "Phase Map",
      what: "For one of your real projects, fill in what the coordinator does at each phase.",
    },
    {
      sheet: "Phase Checklist",
      what: "Run these six questions at the start of every phase or major handoff.",
    },
    {
      sheet: "Role Boundaries",
      what: "Coordination is not authority. Mark each scenario: who owns it, what's your support role.",
    },
  ],
  "/templates/raid_log_starter.xlsx": [
    {
      sheet: "RAID log",
      what: "One row per entry. Columns: ID, Type, Description, Trigger, Impact, Likelihood, Mitigation, Owner, Follow-up, Status.",
    },
    {
      sheet: "Instructions",
      what: "Field-by-field guide to what goes in each column — read this first.",
    },
  ],
  "/templates/written_voice_editing_pass.xlsx": [
    {
      sheet: "Editing Pass",
      what: "For five emails of consequence this week, paste the draft, then the edited version.",
    },
    {
      sheet: "Subject Lines",
      what: "Pull your last 10 sent emails. Rate each subject line, then rewrite the weak ones.",
    },
    {
      sheet: "Bad News",
      what: "Pick a piece of bad news you need to deliver this month.",
    },
  ],
};
